### ISSUE TITLE
README Know Bugs

### ISSUE THREAD

**Issue by eddy5641** [eddy5641/LegendaryClient#1]
## These are Known Bugs, Please Don't re-post them, It will only slow down the time that I get to patch the bugs

Known Bugs:
Unable to download patch
No game sounds [An enemy has been slain]
logout crash glitch [Close, logout might work]
custom game multiple starts [uses official lol game client]
must use auto accept queue or legendary client will crash
edit runes doesnt work
can't change rune/mastery pages when in game [uses previous ones]
unable to receive game invite due to rito changes in gameinvite [xmpp -> rtmp]
notifications don't work [the entire popup]
new game modes have RANDOM NAMES
replays do not work [in dev]
lol must be uptodate

**Comment by eddy5641** [comment]
[elitepvpers] Kev- Unable to add friends

**Comment by astrionn** [comment]
[elitepvpers] astrionn  stuck @20% while downloading patch ( idk if it´s the 1st on ur list or something different ...) 
![customclientcrash](https://cloud.githubusercontent.com/assets/7352517/2750467/36abb466-c87d-11e3-93ae-12f055dc3fb5.jpg)

**Comment by eddy5641** [comment]
The first time you launch the client It will take longer to patch. This is because it has to download and extract datadragon. Also make sure that your LOL is uptodate

**Comment by astrionn** [comment]
okay i´ll try and keep you up to date

2014-04-20 17:57 GMT+02:00 eddy5641 notifications@github.com:

**Comment by eddy5641** [comment]
After it finishes patching, it will be fast until riot's next patch

**Comment by astrionn** [comment]
okay seems to work til now :) what is about the wintermint client? does ur
client have some features like the wintermint ?

2014-04-20 18:35 GMT+02:00 eddy5641 notifications@github.com:

**Comment by eddy5641** [comment]
I am posting a video. One feature is aram hack, see enemy team in aram games

**Comment by astrionn** [comment]
u seems like i have to report an issue :/ when i enter a queue it instantly
crashes .... do i have 2 enable or disable autoaccept ?

2014-04-20 18:38 GMT+02:00 astri onn astrionn@gmail.com:

**Comment by eddy5641** [comment]
enable autoaccept

**Comment by astrionn** [comment]
i did so becasue i read this but it crashed

2014-04-20 18:41 GMT+02:00 eddy5641 notifications@github.com:

**Comment by eddy5641** [comment]
idk what regions work though. I only know na works

**Comment by astrionn** [comment]
oh okay i am on euw this will be the issue ..would be very nice if u
contact me when u work on euw , if u will work on it ^^

2014-04-20 18:46 GMT+02:00 eddy5641 notifications@github.com:

**Comment by eddy5641** [comment]
No worries. I actually wanted people from other regions to test this, because that way I would know how to correct it. Are you running an ide like visual studio?

**Comment by astrionn** [comment]
i have visual studio

2014-04-20 18:55 GMT+02:00 eddy5641 notifications@github.com:

**Comment by eddy5641** [comment]
at this location
C:\Riot Games\League of Legends\RADS\projects\lol_air_client\releases\0.0.1.80\deploy
can you send lol.properties [open with notepad/notepad++]
It should look similar to this

host=prod.na1.lol.riotgames.com
xmpp_server_url=chat.na1.lol.riotgames.com
ladderURL=http://www.leagueoflegends.com/ladders
storyPageURL=http://www.leagueoflegends.com/story
lq_uri=https://lq.na1.lol.riotgames.com 
ekg_uri=https://ekg.riotgames.com
regionTag=na
rssStatusURLs=null
lobbyLandingURL=http://landing.leagueoflegends.com/spectator_swf/landingPage.swf
loadModuleChampionDetail=true
featuredGamesURL=http://spectator.na.lol.riotgames.com:80/observer-mode/rest/featured
riotDataServiceDataSendProbability=1.0
platformId=NA1

**Comment by astrionn** [comment]
in the lol.properties file is written :

regionTag=euw
rssStatusURLs=null
host=prod.eu.lol.riotgames.com
xmpp_server_url=chat.eu.lol.riotgames.com
lq_uri=https://lq.eu.lol.riotgames.com
lobbyLandingURL=
http://landing.leagueoflegends.com/spectator_swf/landingPage.swf
loadModuleChampionDetail=true
featuredGamesURL=
http://spectator.eu.lol.riotgames.com:8088/observer-mode/rest/featured
storyPageURL=http://www.leagueoflegends.com/story
ekg_uri=https://ekg.riotgames.com
riotDataServiceDataSendProbability=1.0
platformId=EUW1

2014-04-20 18:57 GMT+02:00 eddy5641 notifications@github.com:

**Comment by eddy5641** [comment]
K I will take a look at PVPNet

**Comment by astrionn** [comment]
okay cool

2014-04-20 19:22 GMT+02:00 eddy5641 notifications@github.com:

**Comment by eddy5641** [comment]
Managed to get euw account. Special thanks to xGoDxViRuSx

**Comment by astrionn** [comment]
Hahah you could have talked to me and i´d get u a smurf lol

2014-04-21 16:47 GMT-03:00 eddy5641 notifications@github.com:
