### ISSUE TITLE
Can't find game if someone dodges/decline queue EUNE

### ISSUE THREAD

**Issue by nairaner** [eddy5641/LegendaryClient#100]
Can be only fixed by restarting client, might affect more regions, but i didn't check.

**Comment by Dispersia** [comment]
I'm assuming this is using solo queue and not team queue page? All of the work in trying to fix queues is on the team queue page so for now just use that. Once it is working good I'll just apply it to the solo queue page. Im going to add a known issues to the readme I guess.

**Comment by eddy5641** [comment]
All regions have this problem. The line that starts the popup, tells the code to not start it up unless you requeue.

**Comment by eddy5641** [comment]
Should be fixed with teamqueue
