### ISSUE TITLE
Exception Connect on PVP, c:\Users\Betty\Desktop\Coding\.. 

### ISSUE THREAD

**Issue by anibalc9** [eddy5641/LegendaryClient#105]
(15/11/2014 2:16) [LOG]: LegendaryClient Has Finished Patching
(15/11/2014 2:16) [LOG]: LegendaryClient Started Up Successfully
(15/11/2014 2:16) [LOG]: Starting Patcher
(15/11/2014 2:16) [EXCEPTION]: A first chance exception was thrown
(15/11/2014 2:16) [EXCEPTION]: No se puede cargar el archivo o ensamblado 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' ni una de sus dependencias. El sistema no puede encontrar el archivo especificado.
(15/11/2014 2:16) [EXCEPTION]:    en System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   en System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(15/11/2014 2:16) [EXCEPTION]: A first chance exception was thrown
(15/11/2014 2:16) [EXCEPTION]: Referencia a objeto no establecida como instancia de un objeto.
(15/11/2014 2:16) [EXCEPTION]:    en PVPNetConnect.PVPNetConnection.Invoke(TypedObject packet) en c:\Users\Betty\Desktop\Coding\LegendaryClient\PVPNetConnect\PVPNetConnection.cs:línea 764
(15/11/2014 2:16) [EXCEPTION]: A first chance exception was thrown
(15/11/2014 2:16) [EXCEPTION]: Referencia a objeto no establecida como instancia de un objeto.
(15/11/2014 2:16) [EXCEPTION]:    en PVPNetConnect.PVPNetConnection.Invoke(TypedObject packet) en c:\Users\Betty\Desktop\Coding\LegendaryClient\PVPNetConnect\PVPNetConnection.cs:línea 764
(15/11/2014 2:16) [EXCEPTION]: A first chance exception was thrown
(15/11/2014 2:16) [EXCEPTION]: Referencia a objeto no establecida como instancia de un objeto.
(15/11/2014 2:16) [EXCEPTION]:    en PVPNetConnect.PVPNetConnection.<Disconnect>b__229()

**Comment by Dispersia** [comment]
Did it not error out or? Upload full log if so

**Comment by eddy5641** [comment]
I should make it log regions too. It might help
