### ISSUE TITLE
Client crash everytime 

### ISSUE THREAD

**Issue by DrTrojan** [eddy5641/LegendaryClient#108]
Hello Eddy
I Downloaded LegendaryClient And when im trying to join the champion select (Custom games only) the Client crash. this does not happen everytime, me and my friend use legendaryclient the crash only happen to one of us in one time and when i / him restart the game and join the custom game again it will crash for the other one. if u didn't understand me you can send me email here : bashar.mohammed4@gmail.com and i will let u control my pc 
last logs : http://pastebin.com/xY5rNFR5

kind regards

**Comment by Dispersia** [comment]
Is it still doing this or not? If not I will close this.

**Comment by DrTrojan** [comment]
Well, i havent test it for awhile

On Wed, Jan 28, 2015 at 2:47 AM, Dispersias Morock <notifications@github.com

**Comment by nairaner** [comment]
checked and no longer crash
