### ISSUE TITLE
4.20?

### ISSUE THREAD

**Issue by ggnoobez** [eddy5641/LegendaryClient#111]
update for 4.20?

**Comment by eddy5641** [comment]
Some regions had server changes. What is your region (send lol.properties as well)

**Comment by juaoose** [comment]
I have not tested LegendaryClient this patch, anyway, I'll leave the lol.properties in here just in case:(Region: LAN)

host=prod.la1.lol.riotgames.com
xmpp_server_url=chat.la1.lol.riotgames.com
lq_uri=https://lq.la1.lol.riotgames.com 
storyPageURL=http://lan.leagueoflegends.com/story
rssStatusURLs=null
regionTag=la1
lobbyLandingURL=http://frontpage.lan.leagueoflegends.com/$localeCode/client/landing
ladderURL=http://www.leagueoflegends.com/ladders
loadModuleChampionDetail=true
featuredGamesURL=http://spectator.la1.lol.riotgames.com:80/observer-mode/rest/featured 
platformId=LA1
ekg_uri=https://ekg.riotgames.com
riotDataServiceDataSendProbability=1.0

**Comment by Dispersia** [comment]
NA appears to be the only one that changed / anyone complained about, so closing. It needs to be compiled to work on NA, but rest of regions work fine.
