### ISSUE TITLE
MissingMethodException

### ISSUE THREAD

**Issue by horato** [eddy5641/LegendaryClient#115]
Hey,
I am getting a MissingMethodException everytime I press play button. Is the problem only on my side?

in PVPNetConnect/RiotObjects/RiotGamesObject.cs line 224
System.MissingMethodException: Konstruktor typu System.Int32 nebyl nalezen.
   v System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)
   v System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)
   v System.Activator.CreateInstance(Type type, Object[] args)
   v PVPNetConnect.RiotObjects.RiotGamesObject.SetFields[T](T obj, TypedObject result) v c:\LegendaryClient\LegendaryClient\PVPNetConnect\RiotObjects\RiotGamesObject.cs:řádek 224

It says that it can't find constructor of type System.Int32

**Comment by Dispersia** [comment]
It shouldn't get to that point. Did you change the type == typeof(Int32) above it to try to remove the spam exceptions by chance? Make sure there is

else if (type == typeof(Int64))
                    {
                        value = Convert.ToInt64(result[intern.Name]);
                    }
                    else if (type == typeof(Int32))
                    {
                        value = Convert.ToInt32(result[intern.Name]);
                    }
                    else if (type == typeof(double))
                    {
                        value = Convert.ToInt64(result[intern.Name]);
                    }

above it.

**Comment by horato** [comment]
I didnt. Its still there. The whole file is untouched, matching the one in my fork.

**Comment by Dispersia** [comment]
Could you post the full log incase something strange is going on behind it?

**Comment by horato** [comment]
http://pastebin.com/TE4yZdVJ
there are.. "few" errors ;D

translation:
Pro typ Int32 byla hodnota buď příliš velká, nebo příliš malá. => The value was either too big or too small for type Int32
Zadaná adresa IP je neplatná. ´=> IP address specified is not valid.
Není nastavena identita aplikace. => App identity is not set.
Byla vyvolána výjimka typu xpnet.PartialTokenException. => Exception of type xpnet.PartialTokenException was raised.
and finally Konstruktor typu System.Int32 nebyl nalezen. => Can't find constructor of type System.Int32

**Comment by horato** [comment]
The "value was either too big or too small" appears in RiotGamesObject on line 170.
 else if (type == typeof(Int32))
                    {
                        value = Convert.ToInt32(result[intern.Name]);
                    }
intern.Name = "purchaseDate"
result array =
![legendaryclient](https://cloud.githubusercontent.com/assets/5708354/5175457/658030e0-743b-11e4-97b5-2f1a453c8a07.jpg)
(1354072140000 in miliseconds = Wed, 28 Nov 2012 03:09:00 GMT
No wonder it crashes heh... but whats the cause and how to fix it? ^^

Callstack points to PVPNetConnect/PublicMethods.cs -> public async Task<ChampionDTO[]> GetAvailableChampions()

**Comment by Dispersia** [comment]
Now that I think about it, we could simply change it to a date instead of keeping it as that huge int. that might be useful. Idk, it's not an actual issue, it just goes past so not 'overly' important to fix atm but definitely something to look into

**Comment by horato** [comment]
soo? is it ok to let it spam exceptions? It makes alot of mess in logs :P

**Comment by Dispersia** [comment]
for now yes. It doesn't actually effect anything, if you want to fix it feel free to make it a Date instead of an int (small conversion), otherwise it won't actually cause a crash or anything and doesn't -need- to be fixed compared to all of the NA changes they're doing (ddragon is gone from NA, dunno lol. need to fix this first)

**Comment by horato** [comment]
oh... Im on eune, we don't have the fancy stuff you do :D What's going on with na?

**Comment by Dispersia** [comment]
Go to my profile and send me an email, we can talk there, this isn't really a place to do this :P (since you don't appear to have one on your profile page)

**Comment by horato** [comment]
What I posted here was all wrong lol, there were missing type checks for elements that came from rito calls inside list ^^
cff977f8f16b621bb8d642b4031a4b7e8efd259e
