### ISSUE TITLE
Client Crashing while patching again

### ISSUE THREAD

**Issue by maxiking913** [eddy5641/LegendaryClient#117]

**Comment by nairaner** [comment]
can you upload the log?

**Comment by eddy5641** [comment]
please read the contributing.md file. Recreate this issue after you read this file.

**Comment by Dispersia** [comment]
On a side note, this was just fixed and will be in the next binary. Sorry for the inconvenience. (for those curious it was deleting the gamestats file after downloading it, so SQLite would kill itself, basically.)
