### ISSUE TITLE
Possible fixes

### ISSUE THREAD

**Issue by juaoose** [eddy5641/LegendaryClient#118]
Hello there,

While looking at the code I noticed there may be some easy to fix troubles, most of them are related to the data gathered before calling ReplayRecorder:
1. In [MainPage.xaml.cs](https://github.com/eddy5641/LegendaryClient/blob/master/LegendaryClient/Windows/MainPage.xaml.cs) at line 624, you can see there is a concatenation between the SpectatorIpAddress and "8088", however, most of the actual SpectatorIpAddresses ports are 80 (There are a few 8088s) 
   Also, a few regions SpectatorIpAdress are outdated/wrong.
   And to avoid the +"8088", you could set the SpectatorIpAdress with the port, like "1.1.1.1:80"
2. In ReplayPage.xaml.cs the way the ReplayRecorder is called is a bit different, and it doesn't seem to work to me, could it be because the ObserverIp is not the same as the SpectatorIp is?

I tried to fix (1) but after getting all the info, it seems to crash while getting endOfGameStats, this is the log:http://pastebin.com/0NHDc5Mk , also, it could not be replayed.

I did not try to push any of the changes because the seemed not to work properly, thats why I leave this here.

Oh and these are the updated SpectatorIpAddresses (Re check them please)
                EUW:    185.40.64.163:80
                EUN:    95.172.65.26:8088
                KR:      110.45.191.11:8088
                BR1:     66.151.33.19:80
                NA1:     192.64.174.163:80
                TR:     95.172.65.242:80 
                LA1:     66.151.33.19:80
                LA2:     66.151.33.19:80
                RU:      95.172.65.242:80
                OC1:     95.172.65.242:80

**Comment by horato** [comment]
Looks like BR server changed their observer IP and EU servers on the other hand must be special with their ports. It should be fine after this push.
As for the replaypage.. I am retarded, There obviously should be spectator port not server port. 
Thanks for the info ;)

in 0c8ab9c652aa33aef2532c0311e63a6fe9ba8746

**Comment by juaoose** [comment]
LAN was also outdated.

I can now test everything since my ISP finally fixed their stuff, I will let you know when I do it.
