### ISSUE TITLE
Public Insta-Pick?

### ISSUE THREAD

**Issue by eddy5641** [eddy5641/LegendaryClient#120]
Do you want to make this feature public. It does not offer a lot of advantages (I just use it because I am lazy)

**Comment by Dispersia** [comment]
Sure, I think it would be fine. I would find it interesting if someone locks it in before you as you know they're using LC :P, but ya go ahead and add it. I'll hopefully start pushing a lot more updates by thursday when all of my exams are done.

**Comment by horato** [comment]
sure, why not.

**Comment by eddy5641** [comment]
Will make it public
