### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by horato** [eddy5641/LegendaryClient#121]
Can I (we) get an updated todo list? I have no idea what to work on now.

**Comment by eddy5641** [comment]
Teambuilder, probabably. It is ultra-buggy at the moment and I need to check if any rtmp calls, they may have changed.

**Comment by eddy5641** [comment]
I will be working on the settings side of things (volume controls, change key bindings for EVERY champ [if you select yasuo, he will have different binds then ahri])

**Comment by horato** [comment]
oke, I will dump the teambuilder calls and then start to work on it.

**Comment by horato** [comment]
Also if anyone gets leaver busted feel free to contact me, I'd like to sniff packets involving this.

**Comment by Dispersia** [comment]
There is an updated TODO in the readme :P, you can work on those also (and if you've messaged me on skype for a few days I don't have access to my computer, only my laptop which doesn't have skype on it which is why I'm not responding, sorry!)

**Comment by horato** [comment]
its fine ^^

**Comment by eddy5641** [comment]
LangFile (I will push a english Language File soon. I might add 中文 as well if I have time)
Some people have been wanting to use LC in a differnt language
