### ISSUE TITLE
Replays\......cs missing

### ISSUE THREAD

**Issue by neskes** [eddy5641/LegendaryClient#128]
Hi,

I tried to compile LegendaryClient and it seems like files are missing.

Replays\EndOfGameStats.cs
Replays\PlayerParticipantStatsSummary.cs
Replays\RawStatDTO.cs
Replays\TeamId.cs
Replays\TeamInfo.cs

// I Already added all the required .dll and linked rtmp-sharp into the project
// I'm also received a error about " 'Change' is not a instancemember and can't be a static class" (Client.cs - LegendaryClient)

would be nice if someone could contact me in skype: neskes2nd

**Comment by horato** [comment]
edy likes to commit uncompilable code... just make the change method static and it should compile since the missing files should be from diferent project

**Comment by neskes** [comment]
Works fine, thanks!
