### ISSUE TITLE
Cryptographic failure while signing assembly

### ISSUE THREAD

**Issue by ghost** [eddy5641/LegendaryClient#129]
I get this error when trying to build the solution...

Error   4   Cryptographic failure while signing assembly 'c:\Users\OnlyTheBest\Documents\GitHub\LegendaryClient\rtmp-sharp\obj\Debug\rtmp-sharp.dll' -- 'Error reading key file 'c:\Users\OnlyTheBest\Documents\keys\wintermint\strong-name-keys\rtmp-sharp.snk' -- The system cannot find the path specified. '

**Comment by RoachxD** [comment]
I think you are not compiling the right Solution or the right Branch of this project, try to download the 'master' Branch

**Comment by ghost** [comment]
Yes, my git somehow didnt download the right files. Rtmp-sharp.dll is now included by default, and I didnt see that.

Solution: Redownload the project.

Thanks!

**Comment by RoachxD** [comment]
No problem!
