### ISSUE TITLE
Crashing before Login Screen

### ISSUE THREAD

**Issue by RoachxD** [eddy5641/LegendaryClient#131]
I was pretty busy yesterday, and today when I woke up I pulled the project and recompiled it..
Everything fine, until I opened the Client and got a Crash right before going to the Login Screen..

Log:

> **(12/7/2014 2:24 PM) [LOG]:** Starting Patcher
> **(12/7/2014 2:24 PM) [LOG]:** LegendaryClient Has Finished Patching
> **(12/7/2014 2:24 PM) [LOG]:** LegendaryClient Started Up Successfully
> **(12/7/2014 2:24 PM) [EXCEPTION]:** A first chance exception was thrown
> **(12/7/2014 2:24 PM) [EXCEPTION]:** Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
> **(12/7/2014 2:24 PM) [EXCEPTION]:**    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
>    at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
> **(12/7/2014 2:24 PM) [LOG]:** DataDragon Version: 4.20.1
> **(12/7/2014 2:24 PM) [LOG]:** Current DataDragon Version: 4.20.1
> **(12/7/2014 2:24 PM) [LOG]:** DDragon Version (LOL Version) = 4.20.1
> **(12/7/2014 2:24 PM) [LOG]:** Client Version: 4.20.1
> **(12/7/2014 2:24 PM) [LOG]:** Air Assets Version: 0.0.1.119
> **(12/7/2014 2:24 PM) [LOG]:** Current Air Assets Version: 0.0.1.119
> **(12/7/2014 2:24 PM) [LOG]:** Trying to detect League of Legends GameClient
> **(12/7/2014 2:24 PM) [LOG]:** League of Legends is located at: C:\Riot Games\League of Legends\
> **(12/7/2014 2:24 PM) [LOG]:** Latest League of Legends GameClient: 0.0.1.68
> **(12/7/2014 2:24 PM) [LOG]:** Checking if League of Legends is Up-To-Date
> **(12/7/2014 2:24 PM) [LOG]:** League of Legends is Up-To-Date
> **(12/7/2014 2:24 PM) [LOG]:** LegendaryClient Has Finished Patching
> **(12/7/2014 2:24 PM) [EXCEPTION]:** A first chance exception was thrown
> **(12/7/2014 2:24 PM) [EXCEPTION]:** Invalid length for a Base-64 char array or string.
> **(12/7/2014 2:24 PM) [EXCEPTION]:**    at System.Convert.FromBase64_Decode(Char\* startInputPtr, Int32 inputLength, Byte\* startDestPtr, Int32 destLength)
> **(12/7/2014 2:24 PM) [EXCEPTION]:** A first chance exception was thrown
> **(12/7/2014 2:24 PM) [EXCEPTION]:** Exception has been thrown by the target of an invocation.
> **(12/7/2014 2:24 PM) [EXCEPTION]:**    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
> **(12/7/2014 2:24 PM) [UNHANDLEDEXCEPTION]:** An unhandled exception was thrown
> **(12/7/2014 2:24 PM) [UNHANDLEDEXCEPTION]:** Exception has been thrown by the target of an invocation.
> **(12/7/2014 2:24 PM) [UNHANDLEDEXCEPTION]:**    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.Delegate.DynamicInvokeImpl(Object[] args)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.DispatcherOperation.InvokeImpl()
>    at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Windows.Threading.DispatcherOperation.Invoke()
>    at System.Windows.Threading.Dispatcher.ProcessQueue()
>    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
>    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
>    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
>    at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
>    at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
>    at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
>    at System.Windows.Threading.Dispatcher.Run()
>    at System.Windows.Application.RunDispatcher(Object ignore)
>    at System.Windows.Application.RunInternal(Window window)
>    at System.Windows.Application.Run(Window window)
>    at System.Windows.Application.Run()
>    at LegendaryClient.App.Main() in c:\Users\Adrian\Desktop\LegendaryClient\LegendaryClient\obj\Debug\App.g.cs:line 0

**Comment by ghost** [comment]
Hi, yes I got this error too. But then I pulled a working version ( the one before your commit ) and it is now working perfectly.

Log:
(2014-12-06 17:47) [LOG]: LegendaryClient Has Finished Patching
(2014-12-06 17:47) [LOG]: LegendaryClient Started Up Successfully
(2014-12-06 17:47) [LOG]: Starting Patcher
(2014-12-06 17:47) [LOG]: DataDragon Version: 4.20.1
(2014-12-06 17:47) [LOG]: Current DataDragon Version: 4.20.1
(2014-12-06 17:47) [LOG]: DDragon Version (LOL Version) = 4.20.1
(2014-12-06 17:47) [LOG]: Client Version: 4.20.1
(2014-12-06 17:47) [LOG]: Air Assets Version: 0.0.1.119
(2014-12-06 17:47) [LOG]: Current Air Assets Version: 0.0.1.119
(2014-12-06 17:47) [LOG]: Trying to detect League of Legends GameClient
(2014-12-06 17:47) [LOG]: League of Legends is located at: C:\Program Files (x86)\Riot\League of Legends\
(2014-12-06 17:47) [LOG]: Latest League of Legends GameClient: 0.0.1.68
(2014-12-06 17:47) [LOG]: Checking if League of Legends is Up-To-Date
(2014-12-06 17:47) [LOG]: League of Legends is Up-To-Date
(2014-12-06 17:47) [LOG]: LegendaryClient Has Finished Patching
(2014-12-06 17:47) [EXCEPTION]: A first chance exception was thrown
(2014-12-06 17:47) [EXCEPTION]: Value cannot be null.
Parameter name: path4
(2014-12-06 17:47) [EXCEPTION]:    at System.IO.Path.Combine(String path1, String path2, String path3, String path4)
(2014-12-06 17:47) [EXCEPTION]: A first chance exception was thrown
(2014-12-06 17:47) [EXCEPTION]: Exception has been thrown by the target of an invocation.
(2014-12-06 17:47) [EXCEPTION]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
(2014-12-06 17:47) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(2014-12-06 17:47) [UNHANDLEDEXCEPTION]: Exception has been thrown by the target of an invocation.
(2014-12-06 17:47) [UNHANDLEDEXCEPTION]:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at System.Windows.Application.Run()
   at LegendaryClient.App.Main() in c:\Users\DeniCevap\Documents\GitHub\LegendaryClient\LegendaryClient\obj\Debug\App.g.cs:line 0

**Comment by nairaner** [comment]
It seems like its problem with the encrypted saved password, maybe you didnt save it after encryption was added and still have it saved as string without encryption.

**Comment by nairaner** [comment]
should work now
