### ISSUE TITLE
Match History "Please upload log to GitHub"

### ISSUE THREAD

**Issue by bziur** [eddy5641/LegendaryClient#132]
It asked me so here it is.

(12/7/2014 9:14 PM) [LOG]: LegendaryClient Has Finished Patching
(12/7/2014 9:14 PM) [LOG]: LegendaryClient Started Up Successfully
(12/7/2014 9:14 PM) [LOG]: Starting Patcher
(12/7/2014 9:14 PM) [LOG]: DataDragon Version: 4.20.1
(12/7/2014 9:14 PM) [LOG]: Current DataDragon Version: 4.20.1
(12/7/2014 9:14 PM) [LOG]: DDragon Version (LOL Version) = 4.20.1
(12/7/2014 9:14 PM) [LOG]: Client Version: 4.20.1
(12/7/2014 9:14 PM) [LOG]: Air Assets Version: 0.0.1.119
(12/7/2014 9:14 PM) [LOG]: Current Air Assets Version: 0.0.1.119
(12/7/2014 9:14 PM) [LOG]: Trying to detect League of Legends GameClient
(12/7/2014 9:14 PM) [LOG]: League of Legends is located at: D:\Games\League of Legends\
(12/7/2014 9:14 PM) [LOG]: Latest League of Legends GameClient: 0.0.1.68
(12/7/2014 9:14 PM) [LOG]: Checking if League of Legends is Up-To-Date
(12/7/2014 9:14 PM) [LOG]: League of Legends is Up-To-Date
(12/7/2014 9:14 PM) [LOG]: LegendaryClient Has Finished Patching
(12/7/2014 9:14 PM) [EXCEPTION]: A first chance exception was thrown
(12/7/2014 9:14 PM) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(12/7/2014 9:14 PM) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(12/7/2014 9:14 PM) [EXCEPTION]: A first chance exception was thrown
(12/7/2014 9:14 PM) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(12/7/2014 9:14 PM) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(12/7/2014 9:14 PM) [EXCEPTION]: A first chance exception was thrown
(12/7/2014 9:14 PM) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(12/7/2014 9:14 PM) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(12/7/2014 9:14 PM) [EXCEPTION]: A first chance exception was thrown
(12/7/2014 9:14 PM) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(12/7/2014 9:14 PM) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(12/7/2014 9:14 PM) [EXCEPTION]: A first chance exception was thrown
(12/7/2014 9:14 PM) [EXCEPTION]: An invalid IP address was specified.
(12/7/2014 9:14 PM) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(12/7/2014 9:14 PM) [LOG]: Connected and logged in as Fellow Foe
(12/7/2014 9:14 PM) [EXCEPTION]: A first chance exception was thrown
(12/7/2014 9:14 PM) [EXCEPTION]: Application identity is not set.
(12/7/2014 9:14 PM) [EXCEPTION]:    at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
(12/7/2014 9:14 PM) [EXCEPTION]: A first chance exception was thrown
(12/7/2014 9:14 PM) [EXCEPTION]: Exception of type 'xpnet.PartialTokenException' was thrown.
(12/7/2014 9:14 PM) [EXCEPTION]:    at xpnet.Encoding.scanLt(Byte[] buf, Int32 off, Int32 end, ContentToken token)
(12/7/2014 9:16 PM) [LOG]: CAP_5x5
(12/7/2014 9:16 PM) [LOG]: BOT
(12/7/2014 9:16 PM) [LOG]: BOT
(12/7/2014 9:16 PM) [LOG]: BOT
(12/7/2014 9:16 PM) [LOG]: BOT
(12/7/2014 9:16 PM) [LOG]: BOT
(12/7/2014 9:16 PM) [LOG]: BOT
(12/7/2014 9:16 PM) [LOG]: BOT

**Comment by nairaner** [comment]
fixed, wait for next release
