### ISSUE TITLE
LEAVER_BUSTER_TAINTED_WARNING IN BR SERVER

### ISSUE THREAD

**Issue by ghost** [eddy5641/LegendaryClient#153]
When I tried join in queue, appears this message:

(Please submit: - LEAVER_BUSTER_TAINTED_WARNING - as an Issue on github explaining what it meant. Thanks!)

Why this happens?

Sorry for bad english, I'm still learning :)

**Comment by Dispersia** [comment]
Thank you! It just means that that error wasn't added as a message to return an actual message for, I'll add it asap
