### ISSUE TITLE
Add support for friend notes

### ISSUE THREAD

**Issue by newchild** [eddy5641/LegendaryClient#155]
It seems it can sometimes crash the client if we don't read the notes correctly

**Comment by RoachxD** [comment]
Found something on their Dev-Site:
![Information](http://puu.sh/dz3lH/5c7b57f70a.jpg)

**Comment by eddy5641** [comment]
I will see if I can pull that out of their chat system.

**Comment by eddy5641** [comment]
not sure if it is in here but I will still put the link up: https://onedrive.live.com/redir?resid=7FABAB39A3B28E1C!833&authkey=!AAcLLN24Lw2YXQ0&ithint=file%2czip

**Comment by eddy5641** [comment]
I have more data but will not add it right now

**Comment by eddy5641** [comment]
Found it. Notes cause crash when they have a comma, I have the fix on my pc but I am working on it so it can read the notes. Notes are attached in a similar way that the group is attached, but some players with null notes do not have it at all. All I have to do now it find out how to update groups + notes

**Comment by eddy5641** [comment]
Finished
