### ISSUE TITLE
Crash if you press home while patcher is going

### ISSUE THREAD

**Issue by rlsa** [eddy5641/LegendaryClient#157]
How to replicate: Start client, quickly push home at the top. Crash and burn.

Error is triggered by the function Prepare2(); insdie of SQLite.cs,
Which is called from LoginPage.cs inside of the LoginPage class.. 
Need to disable home button before patch is complete or add a check to make sure that the champions list inside of SQLite gets initialized before it's called inside of inside of LoginPage.

Exception:
New The name 'New' does not exist in the current context

**Comment by nairaner** [comment]
Fix. Dont know why someone made it that way.
I think it was useless.
