### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by ghost** [eddy5641/LegendaryClient#159]
http://i.imgur.com/bmUBkjW.png

Happened during champion select, not sure what I was doing.
Was using the version: https://github.com/eddy5641/LegendaryClient/commit/1218c6720ef8b990a77d7d3d0dde0ab15dd184e0
^ that was the last commit.

**Comment by newchild** [comment]
Works fine for me in ARAM queue.

**Comment by nairaner** [comment]
nvm, couldnt replicate earlier still need some work

**Comment by ghost** [comment]
It's fixed on my side, no more crashing in the champion select.

**Comment by Dispersia** [comment]
Fixed, will be in next release version.
