### ISSUE TITLE
News tab

### ISSUE THREAD

**Issue by Zer0code** [eddy5641/LegendaryClient#163]
[<I>low priority issue</i>]
<p>On EUW servers for sure and possibly on (all) other server it shows patch notes and some random (possibly placeholder sample news) other news from time around patch 4.15 and it never updates nor are the linked news clickable...<br> If you decide to include news by custom styled web content via awesomium I may probably fix it on my own. <br> If you decide to keep needed resources and third party dependencies low then there will probably be some apis from riot itself or any LoL community website which features official news - just to mention it: ofc we can include our own selected or even created news source channel as well or let user choice between eg. reddit, riot, lolking, xyz ... <p>Please feel free to criticize or offer more alternatives :)

**Comment by horato** [comment]
I was checking that one too, the problem is that riot probably changed news address cause the json you get show exactly what you see, should be looked into..

**Comment by nairaner** [comment]
the news we are using are from before the landing page update. I think we could use news from the page http://euw.leagueoflegends.com/en/rss.xml but it would requires to change from json to xml

**Comment by RoachxD** [comment]
Can we close this as it's fixed now?
