### ISSUE TITLE
Not sure if this will help you...... but.. I figured out how to add bots to custom games..

### ISSUE THREAD

**Issue by rftiiv15** [eddy5641/LegendaryClient#17]
![add_bots](https://cloud.githubusercontent.com/assets/6826256/2936940/86fce9b8-d87b-11e3-9ee7-cf22458126fd.png)

**Comment by eddy5641** [comment]
This will help A LOT but I have to do each champ

**Comment by JamaicanMoose** [comment]
I dont have the skills to do this, but once champ select is finished why not just reimplement it and have a separate declared champion id be pulled on by the custom game.

**Comment by eddy5641** [comment]
Please submit a pull request, it will speed up process by abit

**Comment by eddy5641** [comment]
{
  "$type": "System.Collections.Generic.List`1[[FluorineFx.Messaging.Rtmp.Event.Notify, FluorineFx]], mscorlib",
  "$values": [
    {
      "$type": "FluorineFx.Messaging.Rtmp.Event.FlexInvoke, FluorineFx",
      "CmdData": null,
      "Data": null,
      "InvokeId": 83,
      "ServiceCall": {
        "$type": "FluorineFx.Messaging.Rtmp.Service.PendingCall, FluorineFx",
        "Result": null,
        "IsSuccess": false,
        "ServiceMethodName": null,
        "ServiceName": null,
        "Arguments": {
          "$type": "System.Object[], mscorlib",
          "$values": [
            {
              "$type": "FluorineFx.Messaging.Messages.RemotingMessage, FluorineFx",
              "source": null,
              "operation": "selectBotChampion",
              "headers": {
                "$type": "FluorineFx.ASObject, FluorineFx",
                "DSId": "94DE219F-8819-CC3B-0DD4-0751C6EBDFC6",
                "DSRequestTimeout": 60,
                "DSEndpoint": "my-rtmps"
              },
              "body": {
                "$type": "System.Object[], mscorlib",
                "$values": [
                  37,
                  {
                    "$type": "FluorineFx.ASObject, FluorineFx",
                    "champion": {
                      "$type": "FluorineFx.ASObject, FluorineFx",
                      "ownedByYourTeam": true,
                      "skinName": "Sona",
                      "banned": false,
                      "displayName": "Sona",
                      "freeToPlay": false,
                      "championData": {
                        "$type": "FluorineFx.ASObject, FluorineFx",
                        "passiveIcon": "Sona_PowerChordCharged.dds",
                        "abilityIcon1": "Sona_HymnofValor.dds",
                        "abilityIcon2": "Sona_AriaofPerseverance.dds",
                        "abilityIcon3": "Sona_SongofDiscord.dds",
                        "skinInfo": {
                          "$type": "FluorineFx.ASObject, FluorineFx",
                          "37001": {
                            "$type": "FluorineFx.ASObject, FluorineFx",
                            "skinId": 37001,
                            "skinIndex": 1,
                            "name": "MuseSona",
                            "TypeName": null
                          },
                          "37002": {
                            "$type": "FluorineFx.ASObject, FluorineFx",
                            "skinId": 37002,
                            "skinIndex": 2,
                            "name": "MetalSona",
                            "TypeName": null
                          },
                          "37003": {
                            "$type": "FluorineFx.ASObject, FluorineFx",
                            "skinId": 37003,
                            "skinIndex": 3,
                            "name": "SilentNightSona",
                            "TypeName": null
                          },
                          "37004": {
                            "$type": "FluorineFx.ASObject, FluorineFx",
                            "skinId": 37004,
                            "skinIndex": 4,
                            "name": "GuqinSona",
                            "TypeName": null
                          },
                          "37005": {
                            "$type": "FluorineFx.ASObject, FluorineFx",
                            "skinId": 37005,
                            "skinIndex": 5,
                            "name": "PaxSona",
                            "TypeName": null
                          },
                          "TypeName": null
                        },
                        "abilityIcon4": "Sona_Crescendo.dds",
                        "championId": 37,
                        "searchTags": {
                          "$type": "System.Object[], mscorlib",
                          "$values": [
                            "support"
                          ]
                        },
                        "attackRank": 5,
                        "searchTagsSecondary": {
                          "$type": "System.Object[], mscorlib",
                          "$values": [
                            "mage"
                          ]
                        },
                        "defenseRank": 2,
                        "skinName": "Sona",
                        "magicRank": 8,
                        "difficultyRank": 1,
                        "TypeName": null
                      },
                      "searchTags": {
                        "$type": "System.Object[], mscorlib",
                        "$values": [
                          "support"
                        ]
                      },
                      "secondarySearchTags": {
                        "$type": "System.Object[], mscorlib",
                        "$values": [
                          "mage"
                        ]
                      },
                      "botEnabled": true,
                      "championId": 37,
                      "owned": true,
                      "championSkins": {
                        "$type": "FluorineFx.AMF3.ArrayCollection, FluorineFx",
                        "$values": [
                          {
                            "$type": "FluorineFx.ASObject, FluorineFx",
                            "lastSelected": false,
                            "championId": 37,
                            "owned": false,
                            "freeToPlayReward": false,
                            "skinIndex": 3,
                            "skinId": 37003,
                            "stillObtainable": false,
                            "purchaseDate": 0,
                            "endDate": 0,
                            "winCountRemaining": 0,
                            "dataVersion": null,
                            "futureData": null,
                            "TypeName": "com.riotgames.platform.catalog.champion.ChampionSkinDTO"
                          },
                          {
                            "$type": "FluorineFx.ASObject, FluorineFx",
                            "lastSelected": false,
                            "championId": 37,
                            "owned": false,
                            "freeToPlayReward": false,
                            "skinIndex": 4,
                            "skinId": 37004,
                            "stillObtainable": true,
                            "purchaseDate": 0,
                            "endDate": 0,
                            "winCountRemaining": 0,
                            "dataVersion": null,
                            "futureData": null,
                            "TypeName": "com.riotgames.platform.catalog.champion.ChampionSkinDTO"
                          },
                          {
                            "$type": "FluorineFx.ASObject, FluorineFx",
                            "lastSelected": false,
                            "championId": 37,
                            "owned": false,
                            "freeToPlayReward": false,
                            "skinIndex": 1,
                            "skinId": 37001,
                            "stillObtainable": true,
                            "purchaseDate": 0,
                            "endDate": 0,
                            "winCountRemaining": 0,
                            "dataVersion": null,
                            "futureData": null,
                            "TypeName": "com.riotgames.platform.catalog.champion.ChampionSkinDTO"
                          },
                          {
                            "$type": "FluorineFx.ASObject, FluorineFx",
                            "lastSelected": false,
                            "championId": 37,
                            "owned": false,
                            "freeToPlayReward": false,
                            "skinIndex": 2,
                            "skinId": 37002,
                            "stillObtainable": true,
                            "purchaseDate": 0,
                            "endDate": 0,
                            "winCountRemaining": 0,
                            "dataVersion": null,
                            "futureData": null,
                            "TypeName": "com.riotgames.platform.catalog.champion.ChampionSkinDTO"
                          },
                          {
                            "$type": "FluorineFx.ASObject, FluorineFx",
                            "lastSelected": true,
                            "championId": 37,
                            "owned": true,
                            "freeToPlayReward": false,
                            "skinIndex": 5,
                            "skinId": 37005,
                            "stillObtainable": true,
                            "purchaseDate": 1374394443000.0,
                            "endDate": 0,
                            "winCountRemaining": 0,
                            "dataVersion": null,
                            "futureData": null,
                            "TypeName": "com.riotgames.platform.catalog.champion.ChampionSkinDTO"
                          }
                        ]
                      },
                      "freeToPlayReward": false,
                      "active": true,
                      "ownedByEnemyTeam": true,
                      "description": "Maven of the Strings",
                      "purchaseDate": 1307689431000.0,
                      "endDate": 0,
                      "winCountRemaining": 0,
                      "dataVersion": null,
                      "futureData": null,
                      "TypeName": "com.riotgames.platform.catalog.champion.ChampionDTO"
                    },
                    "botSkillLevel": 0,
                    "botSkillLevelName": "Basic",
                    "teamId": "100",
                    "pickTurn": 0,
                    "badges": 0,
                    "teamName": null,
                    "summonerName": "Sona bot",
                    "pickMode": 0,
                    "isGameOwner": false,
                    "isMe": false,
                    "team": 0,
                    "summonerInternalName": "bot_Sona_100",
                    "dataVersion": null,
                    "futureData": null,
                    "TypeName": "com.riotgames.platform.game.BotParticipant"
                  }
                ]
              },
              "timestamp": 0,
              "destination": "gameService",
              "clientId": null,
              "messageId": "48317C8F-44FB-A9D7-3380-97EDB14696EE",
              "timeToLive": 0
            }
          ]
        },
        "Status": 1,
        "Exception": null
      },
      "ConnectionParameters": null,
      "EventType": 2,
      "Header": {
        "$type": "FluorineFx.Messaging.Rtmp.RtmpHeader, FluorineFx",
        "ChannelId": 3,
        "DataType": 17,
        "Size": 1647,
        "StreamId": 0,
        "Timer": 2756,
        "IsTimerRelative": true
      },
      "Object": null,
      "Timestamp": 2756,
      "ExtendedTimestamp": -1,
      "DataType": 17,
      "Source": null,
      "HasSource": false
    },
    {
      "$type": "FluorineFx.Messaging.Rtmp.Event.FlexInvoke, FluorineFx",
      "CmdData": null,
      "Data": null,
      "InvokeId": 71,
      "ServiceCall": {
        "$type": "FluorineFx.Messaging.Rtmp.Service.PendingCall, FluorineFx",
        "Result": null,
        "IsSuccess": false,
        "ServiceMethodName": "_result",
        "ServiceName": null,
        "Arguments": {
          "$type": "System.Object[], mscorlib",
          "$values": [
            {
              "$type": "DSK, LoLNotes",
              "CorrelationId": "48317C8F-44FB-A9D7-3380-97EDB14696EE",
              "CorrelationIdBytes": "H1|Dû©×3€—í±F–î",
              "Body": null,
              "ClientId": "94EB6928-4B0D-EE6E-5075-C68E38C287F0",
              "ClientIdBytes": "”ëi(K\rînPuÆŽ8Â‡ð",
              "Destination": null,
              "Headers": null,
              "MessageId": "94EB6936-F11F-0105-41F9-163DE52D7092",
              "MessageIdBytes": "”ëi6ñ\u001f\u0001\u0005Aù\u0016=å-p’",
              "TimeStamp": 1385528409217,
              "TimeToLive": 0
            }
          ]
        },
        "Status": 1,
        "Exception": null
      },
      "ConnectionParameters": null,
      "EventType": 2,
      "Header": {
        "$type": "FluorineFx.Messaging.Rtmp.RtmpHeader, FluorineFx",
        "ChannelId": 3,
        "DataType": 17,
        "Size": 95,
        "StreamId": 0,
        "Timer": 0,
        "IsTimerRelative": false
      },
      "Object": null,
      "Timestamp": 0,
      "ExtendedTimestamp": -1,
      "DataType": 17,
      "Source": null,
      "HasSource": false
    }
  ]
}
|Sona bot example, remember this

**Comment by eddy5641** [comment]
Remember this aswell

**Comment by eddy5641** [comment]
{"champions": [
        {"id":266,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":103,"active":true,"botEnabled":false,"freeToPlay":true,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":84,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":12,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":32,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":34,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":1,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":22,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":53,"active":true,"botEnabled":true,"freeToPlay":true,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":63,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":201,"active":true,"botEnabled":false,"freeToPlay":true,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":51,"active":true,"botEnabled":true,"freeToPlay":true,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":69,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":31,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":42,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":122,"active":true,"botEnabled":true,"freeToPlay":true,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":131,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":119,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":36,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":60,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":28,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":81,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":9,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":114,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":105,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":3,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":41,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":86,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":79,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":104,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":120,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":74,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":39,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":40,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":59,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":24,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":126,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":222,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":43,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":30,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":38,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":55,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":10,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":85,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":121,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":96,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":7,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":64,"active":true,"botEnabled":false,"freeToPlay":true,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":89,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":127,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":236,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":117,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":99,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":54,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":90,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":57,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":11,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":21,"active":true,"botEnabled":true,"freeToPlay":true,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":62,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":82,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":25,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":267,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":75,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":111,"active":true,"botEnabled":false,"freeToPlay":true,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":76,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":56,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":20,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":2,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":61,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":80,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":78,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":133,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":33,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":58,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":107,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":92,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":68,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":13,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":113,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":35,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":98,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":102,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":27,"active":true,"botEnabled":false,"freeToPlay":true,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":14,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":15,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":72,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":37,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":16,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":50,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":134,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":91,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":44,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":17,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":412,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":18,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":48,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":23,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":4,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":29,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":77,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":6,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":110,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":67,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":45,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":161,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":254,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":112,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":8,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":106,"active":true,"botEnabled":false,"freeToPlay":true,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":19,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":101,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":5,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":157,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":83,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":154,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":238,"active":true,"botEnabled":false,"freeToPlay":false,"botMmEnabled":false,"rankedPlayEnabled":true},
        {"id":115,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":26,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true},
        {"id":143,"active":true,"botEnabled":true,"freeToPlay":false,"botMmEnabled":true,"rankedPlayEnabled":true}
    ]
}

**Comment by rftiiv15** [comment]
My client just hangs on "logging in"

**Comment by JamaicanMoose** [comment]
If you do not have the closed beta version then it will do that.

**Comment by rftiiv15** [comment]
I am a beta user.. I haves dev key. Where is the closed beta version?

-DayLan Carlsted

**Comment by eddy5641** [comment]
It was emailed

**Comment by eddy5641** [comment]
This is irreverent if you do not want to talk on bots in this issue, do not reopen it
