### ISSUE TITLE
Queue time something is wrong.

### ISSUE THREAD

**Issue by ghost** [eddy5641/LegendaryClient#173]
Okay so basically something weird just happened, no errors.
Basically was in a normals queue and someone dodged and the queue kept going for over 10mins..(normals) and then clicked leave and continued to find another game, still kept being long.
Restarted the client Queue only took 12seconds.

Not sure if it's a bug or just random.

**Comment by eddy5641** [comment]
This is a bug. Sometimes when you queue, and someone dodges it will not load up the the queuepop for the next game. I will try to fix it

**Comment by Dispersia** [comment]
Are you on 2.2.0.6? That shouldn't happen in that version (in lower versions it might have), if you're still on the newer version then ya it needs looked into.

**Comment by ghost** [comment]
I always like to keep my fork up to date so i can run with newer updates, so I'm using the latest, whatever that is.

**Comment by nairaner** [comment]
should be fixed
