### ISSUE TITLE
Queue Pop not Showing.

### ISSUE THREAD

**Issue by RoachxD** [eddy5641/LegendaryClient#176]
Queue Pop not showing after someone dodges in Champ Select.

**Comment by ghost** [comment]
Yes, I've noticed this too. Often friends tell me I've dodged but according to the client we are still in queue - the queue timer still ticks on as if no Queue Pop is triggered.

Not really sure where to look into this.

**Comment by mastropeos** [comment]
i managed to fix this!i restarted my client :D(still looking for perma solution)

**Comment by eddy5641** [comment]
I will look what the lol client does when somebody does not accept queue

**Comment by eddy5641** [comment]
Hope that this works now

**Comment by RoachxD** [comment]
Closed for the moment, if this happens again, it will be re-opened!
