### ISSUE TITLE
Login Issue

### ISSUE THREAD

**Issue by JamaicanMoose** [eddy5641/LegendaryClient#18]
The given key was not present in the dictionary.

Does anyone know what this means?

**Comment by JamaicanMoose** [comment]
nvm i used a version i pulled from your website using a crawler since i couldnt find the public releace downloads. I see you fixed this issue already

**Comment by JamaicanMoose** [comment]
I am evidently very stupid and was blind enough not to notice that you require a dev key to use the launcher (except curiously the newest pre-built binary). Would it be possible in any way to obtain one of these keys, or are all of the future builds going to be open (as when i compile the newest source it is locked)

**Comment by eddy5641** [comment]
You will not require a dev key, dev keys just unlock certain features, for example, bypassing they client's update system but this only works for an up to date client. If you would like to enable dev mode I believe you can use !~devkey-publicdev~!. If you would like a private key, please message me.

**Comment by rftiiv15** [comment]
I would love a private dev key. 
Email me at rftiiv15@gmail.com 

-DayLan Carlsted

**Comment by JamaicanMoose** [comment]
I really dont know what this problem is, it persists in the new version and it happens even if I reinstall. It wont even let me log in anymore.

**Comment by eddy5641** [comment]
on the login page, in the top right hand corner please make sure it says 4.8.test
