### ISSUE TITLE
Source (from experimental) 

### ISSUE THREAD

**Issue by rftiiv15** [eddy5641/LegendaryClient#21]
I get "champions table" not found error from sql when trying to debug.  Any solutions?

**Comment by eddy5641** [comment]
C:\Riot Games\League of Legends\RADS\projects\lol_air_client\releases\0.0.1.88\deploy\assets\data\gameStats
Try copying all of the gameStats files

**Comment by eddy5641** [comment]
if braum is missing try copying these files
dragontail-4.7.8.tgz.\4.7.8\img\champion
into champion
and
C:\Riot Games\League of Legends\RADS\projects\lol_air_client\releases\0.0.1.88\deploy\assets\images\champions
into champions
