### ISSUE TITLE
Tr server is missing on the launcher

### ISSUE THREAD

**Issue by AliEnsarTunc** [eddy5641/LegendaryClient#22]
Title says it all.

**Comment by eddy5641** [comment]
In order to add a server I will need files
C:\Riot Games\League of Legends\RADS\projects\lol_air_client\releases\0.0.1.88\deploy\lol.properties
Open that in a text editor and copy and paste it. Work will start once this is done

**Comment by AliEnsarTunc** [comment]
host=prod.tr.lol.riotgames.com
xmpp_server_url=chat.tr.lol.riotgames.com
lq_uri=https://lq.tr.lol.riotgames.com
storyPageURL=http://tr.leagueoflegends.com/story
rssStatusURLs=null
regionTag=tr
lobbyLandingURL=http://landing.leagueoflegends.com/spectator_swf/landingPage.swf
ladderURL=http://competitive.tr.leagueoflegends.com/tr-tr/ladders
loadModuleChampionDetail=true
featuredGamesURL=http://spectator.tr.lol.riotgames.com:80/observer-mode/rest/featured 
platformId=TR1
ekg_uri=https://ekg.riotgames.com
riotDataServiceDataSendProbability=1.0

**Comment by eddy5641** [comment]
Idk if it works, look at the source and build a copy of legendaryclient then login

**Comment by AliEnsarTunc** [comment]
The thing is i can't do that :P

**Comment by JamaicanMoose** [comment]
If you make all the neccisary changes on your fork, then I will build it for you. Just commit them and comment on this issue when its ready.

Best Wishes
- TrollinTeemo

**Comment by eddy5641** [comment]
Will be in my release when I upload it

**Comment by GodLesZ** [comment]
Was added in 3e3b18e25a892c395dd2048be280dac0eb31e6eb and should be closed if confirmed.

**Comment by eddy5641** [comment]
Added and closed
