### ISSUE TITLE
Startup Issue

### ISSUE THREAD

**Issue by JamaicanMoose** [eddy5641/LegendaryClient#24]
Legendary Client stops working right as it is loading the featured games. Not sure if this is causing the problem, or if it is something that loads at the same time.

**Comment by spix18** [comment]
Got the same error , it was working before =/

**Comment by eddy5641** [comment]
looks like it sometimes stops because it is unable to load the featured games champ icons and background and the spectate profile page [to see your wins but when it looks up a friend automatically]
