### ISSUE TITLE
Language file is missing

### ISSUE THREAD

**Issue by nairaner** [eddy5641/LegendaryClient#25]
Where is it suposed to be located so i can copy it there?
Also on EUN featured games and news doesnt show up.

**Comment by eddy5641** [comment]
C:\Riot Games\League of Legends\RADS\projects\lol_air_client\releases\0.0.1.88\deploy
open lol.properties in notepad Paste it here

**Comment by nairaner** [comment]
regionTag=eune
rssStatusURLs=null
host=prod.eun1.lol.riotgames.com
xmpp_server_url=chat.eun1.lol.riotgames.com
lq_uri=https://lq.eun1.lol.riotgames.com
lobbyLandingURL=http://landing.leagueoflegends.com/spectator_swf/landingPage.swf
loadModuleChampionDetail=true
featuredGamesURL=http://spectator.eu.lol.riotgames.com:8088/observer-mode/rest/featured
storyPageURL=http://www.leagueoflegends.com/story
ekg_uri=https://ekg.riotgames.com
riotDataServiceDataSendProbability=1.0
platformId=EUN1

**Comment by eddy5641** [comment]
the language currently only supports English, but I can make it support other languages. A fix for featured games has been done. A release to pre-testers will be sent soon.

**Comment by nairaner** [comment]
I wanted to use english and ive had downloaded both EU and NA versions of english, but the Legendaryclient still couldnt find them. Ive reinstalled whole league and it worked
