### ISSUE TITLE
"Your username or password is incorrect!"

### ISSUE THREAD

**Issue by koreanoverlord** [eddy5641/LegendaryClient#28]
Tried on several accounts, it simply denies my login info is correct.

Sometimes it will give me "Riots servers are currently unavailable." as well.

This is on NA server, I am using 4.8.test. I also have tried on 2 different PCs.

Solved: Symbols in the password fails the login

**Comment by nairaner** [comment]
try to change 4.8.test to 4.9.1

**Comment by koreanoverlord** [comment]
And where would I change that?

**Comment by nairaner** [comment]
on login page in top right corner

**Comment by koreanoverlord** [comment]
Sadly, it's still not working.

**Comment by naeem76** [comment]
I have login problems unless i forcefully change client version to 4.9.1
It has problems calculating the Client Version, the result comes up as 4.8.text
Haven't looked ino the problem yet

**Comment by eddy5641** [comment]
It was a fix for 4.8 patch. The textbox was implemented so LC would copy ddragon's version but that was overwritten

**Comment by eddy5641** [comment]
Will be fixed in the release what I upload it
