### ISSUE TITLE
PBE Crashes.

### ISSUE THREAD

**Issue by Blackdick** [eddy5641/LegendaryClient#295]
as you can see in the title.

everytime i try to play on the PBE it crashes :(

**Comment by secretdataz** [comment]
Please post your crashlog so we can see what causes your crash.

**Comment by Blackdick** [comment]
Sorry for the delay, 

http://pastebin.com/JLBY6aw3

**Comment by eddy5641** [comment]
LoginPage.xaml.cs :line 104 at System.IO.Path.Combine(String path1, String path2, String path3, String path4)

**Comment by Blackdick** [comment]
Eddy, what’s that supposed to mean?


Anyway, i managed to get to the login page, but everytime i enter my information and log-in it crashes immediately.


Here’s the last log file:

http://pastebin.com/HfmLWrX7

**Comment by secretdataz** [comment]
Looks like converting account ID into Int32 is the issue.
(TypedObject.cs line 62)  return Convert.ToInt32((double)val);
(PVPNetConnection.cs line 594)  accountID = (int)body.GetTO("accountSummary").GetInt("accountId");

**Comment by Blackdick** [comment]
What am i supposed to do now? should i wait until you guys fix it ?


I really appreciate your help.

**Comment by nairaner** [comment]
can you tell me you name on PBE?

**Comment by eddy5641** [comment]
Try now, if not fixed it should be a different error but there was a big switch from pvpnet to rtmp-sharp

**Comment by Blackdick** [comment]
Hi ed,


unfortunately its still crashing :(

here’s the log : http://pastebin.com/RkRKSppP

**Comment by nairaner** [comment]
try using latest dev client https://ci.appveyor.com/api/buildjobs/a50qdmg7ksyrg2t8/artifacts/LegendaryClient.zip
