### ISSUE TITLE
EUW Issue

### ISSUE THREAD

**Issue by MichaelZer0** [eddy5641/LegendaryClient#37]
Hi Eddy :D 
I found a problem in the library PVPNetConnect.
I think that the IP of the EUW Server is wrong.
The DLL says this address:
 eu.lol.riotgames.com

But instead of lol.properties I find these ips:

---

regionTag=euw
rssStatusURLs=null
host=prod.euw1.lol.riotgames.com
xmpp_server_url=chat.euw1.lol.riotgames.com
lq_uri=https://lq.euw1.lol.riotgames.com
lobbyLandingURL=http://landing.leagueoflegends.com/spectator_swf/landingPage.swf
loadModuleChampionDetail=true
featuredGamesURL=http://spectator.euw1.lol.riotgames.com:80/observer-mode/rest/featured
storyPageURL=http://www.leagueoflegends.com/story
ekg_uri=https://ekg.riotgames.com
riotDataServiceDataSendProbability=1.0
platformId=EUW1

---

In fact, your client gives me this error: "Riots servers are currently unavailable."
Could you solve this problem?

PS: Congratulations for the beautiful client :smile: and sorry for my English

**Comment by eddy5641** [comment]
fixed
You do not need to apologize for your English. Mine isn't the best as well

**Comment by MichaelZer0** [comment]
Thanks a lot :heart:
Bye :D
