### ISSUE TITLE
Error with invitation ranked

### ISSUE THREAD

**Issue by BraveStarr1** [eddy5641/LegendaryClient#39]
No Invitation Id was received. Report to Eddy5641 [https://github.com/Eddy5641/LegendaryClient/issues/new]

**Comment by eddy5641** [comment]
This is a known issue. I am looking into it

**Comment by eddy5641** [comment]
Fixed, but working on lobby status now

**Comment by eddy5641** [comment]
Fixed. Should be in next release. I would not recommend you to play this in ranked
