### ISSUE TITLE
com.riotgames.platform.matchmaking

### ISSUE THREAD

**Issue by eddy5641** [eddy5641/LegendaryClient#4]
Anybody want to help with pvpnetconnect?

**Comment by kevvv** [comment]
If I knew more about C# or understood how it worked I'd be down to help.  Spent way too much time in C++ code :(

**Comment by eddy5641** [comment]
Idk what the rtmp server for game invites because riot changes game invites from xmpp based to rtmp based

**Comment by eddy5641** [comment]
Found server
