### ISSUE TITLE
Used to be able to download the whole repo and compile...

### ISSUE THREAD

**Issue by kevvv** [eddy5641/LegendaryClient#42]
Been about a month since the last time I decided to pull from this repo, but as of now whenever I pull it I end up getting errors with the LegendaryClient.csproj on line 89.  Then even after downloading an older version of that I'm still missing multiple references that I have found and attempted to add but still have no success on compiling it.  How the hell are people even still able to use this?

**Comment by eddy5641** [comment]
https://github.com/eddy5641/LegendaryClient/commit/6a9a4779c47407186dfc932f8153181777fb5404
The merge to master, screwed up everything
If you are missing multiple references tell me the references and I will send them to you

**Comment by kevvv** [comment]
I was missing rtmp-sharp, couldn't find it anywhere in the file, also could not find newtonsoft.json.  But that was after being forced to revert back to an old LegendaryClient.csproj

**Comment by eddy5641** [comment]
Rtmp-sharp, should not bee needed for https://github.com/eddy5641/LegendaryClient/commit/6a9a4779c47407186dfc932f8153181777fb5404 you should be able to delete it. Download json.net [newtonsoft.json should be solved] from nuget if you need more look here https://www.nuget.org/packages/newtonsoft.json/

**Comment by eddy5641** [comment]
Closed, re-open this if you need it
