### ISSUE TITLE
Login Acc lvl30 (EUW)

### ISSUE THREAD

**Issue by mesofranico** [eddy5641/LegendaryClient#43]
I cant login with my acc lvl30 but with new acc lvl1 all work!

AccLvL30-> http://imgup.com/data/images/19029.jpg

**Comment by eddy5641** [comment]
Looking into correcting this

**Comment by eddy5641** [comment]
Relates to ranked, it fails to load ranked games correctly because it tries to find what rank you are if you are lv 30

**Comment by eddy5641** [comment]
Fixed
