### ISSUE TITLE
Visual Studio 2013

### ISSUE THREAD

**Issue by mesofranico** [eddy5641/LegendaryClient#44]
I cant open project (can) but have this error

LegendaryClient\LegendaryClient.csproj: Error on line 0. Expected 'ENCODING' but found 'utf-8'.

**Comment by kevvv** [comment]
Can agree with this, you might be able to get it to load with one of the LegendaryClient.csproj files from the experiements-dev, but that one probably won't work.  This is a good example of merging gone wrong :(

**Comment by spix18** [comment]
Got the same error =/

**Comment by eddy5641** [comment]
Replace with this 
https://github.com/eddy5641/LegendaryClient/blob/6a9a4779c47407186dfc932f8153181777fb5404/LegendaryClient/LegendaryClient.csproj
merged master... into experiments-dev opps

**Comment by kevvv** [comment]
End up getting an error stating that GameInviteTest.xaml is non existent, after removing that even more errors continue to pop up.  

Here is a screen shot:  http://i.imgur.com/FYJ8PDE.png

I think the master branch is pretty well messed up at this point.

It seems like all the "<<<<<< Head" and ">>>>>> master" things from merging really screwed things up in visual studio.

**Comment by eddy5641** [comment]
Should now be solved :P

**Comment by kevvv** [comment]
o.O How did something change with no commits or such? (I rarely use github holy crap D: )

**Comment by eddy5641** [comment]
Removed the master merge commit from visual studio
I used these commands
git rebase -i HEAD~5
git push origin experiments-dev

**Comment by kevvv** [comment]
Well I switched to using the Experiments-Dev build, it can at least load without an error, but compiling it happens to be missing: rtmp-sharp (removed it tried again), GameInviteTest.xaml.cs (removed it again),  GameInvitePopup.xaml.cs (removed GameInvitePopup.xaml, then it was pointing to a wrong PVPNetConnect.dll so I fixed that up, attempting to compile after that brought out some missing things regarding the GameInvitePopup (I kind of expected that...) and then some things like 'Trade' does not exist in the namespace 'PVPNetConnect.RiotObjects.Platform'  

It seriously looks like there are some files missing from this and I really don't know how anyone is even using this at the moment.
