### ISSUE TITLE
New Version Problem

### ISSUE THREAD

**Issue by juaoose** [eddy5641/LegendaryClient#45]
I just downloaded the last release and I keep getting this.

Yes, I have my League Of Legends folder inside.

![image](https://cloud.githubusercontent.com/assets/994594/3484341/0864b638-03a7-11e4-84f7-32716925fc97.png)

**Comment by kevvv** [comment]
At least you can get something that runs ;3

**Comment by eddy5641** [comment]
did you run as admin? there are some problems where it has to be run as administrator because it came from "an unsafe location" and microsoft blocks some features. Running as admin can correct this if this is your problem

**Comment by spix18** [comment]
it working for me ( euw patch 4.11 with the new DataDragon 4.11.3) , you just need to update your PVPNetConnect.dll.

here is my https://www.dropbox.com/s/n4os8bfp08uthxj/PVPNetConnect.zip , that works for me.

http://i.imgur.com/zsxUs2A.jpg ( screenshot)

if your client still closing itself , try to delete everything and create a new folder and let him download and copy everything.

ps: invites and team queue still not working , they crash your client :p.

**Comment by juaoose** [comment]
Tested what @Kayo99 and @eddy5641 suggested but none worked, the client stops working when checking for existing League of Legends installation.

**Comment by kevvv** [comment]
Are you guys testers and were given a .exe or are you compiling it?

**Comment by spix18** [comment]
@kevvv im only a tester , i got this update pvpnetconnect from a site , eddy know it :p

**Comment by spix18** [comment]
Ps : i'm running windows 8.1 64bit

**Comment by eddy5641** [comment]
@kevvv All beta testers have a beta key, inputting this kill allows them to download the latest version (as planned for the next release). All programmers are expected to compile it by hand because it is easier to do it that way.

**Comment by kevvv** [comment]
@eddy5641 I'm guessing you're closed for beta testers then?

**Comment by eddy5641** [comment]
no, i will be accepting up to 50, i only have 16

**Comment by kevvv** [comment]
Probably the wrong place, but I'd be more than willing to be a beta tester.

**Comment by eddy5641** [comment]
email me at ic.eddy5641@gmail.com to receive a beta key [don't want it public]

**Comment by juaoose** [comment]
Nothing seems to make it past that =(

**Comment by eddy5641** [comment]
Where LegendaryClient [.exe] is create a new folder called RADS
In rads create a text document called:
VERSION_LOL [If .exe was hidden for legendaryclient you will have to show file extentions to remove .txt
In VERSION_LOL put in
0.0.0.99

In rads create a new folder called
projects
Now navigate to this location
C:\Riot Games\League of Legends\RADS\projects
Copy [ctrl + c, not drag and drop] lol_game_client into projects [Rads folder containing VERSION_LOL]

Now go here:
C:\Riot Games\League of Legends\RADS\projects\lol_launcher\releases\0.0.0.212\deploy
or C:\Riot Games\League of Legends\RADS\projects\lol_launcher\releases\ [highest number] \deploy

Copy RiotRadsIO.dll into Legendaryclient's rads

Tell me if this solves the problem

The rads folder should look like this
![how should look](https://cloud.githubusercontent.com/assets/6468338/3504376/9f78eafc-0646-11e4-8658-f8d68d72509c.PNG)

**Comment by eddy5641** [comment]
"96f56bc2e656062772f07b676e6e890c9bf5ed20" SHA1 : invid2137627

**Comment by juaoose** [comment]
This worked, thanks eddy.

Closing issue.
