### ISSUE TITLE
Sending Bug Reports

### ISSUE THREAD

**Issue by eddy5641** [eddy5641/LegendaryClient#50]
Copy icdebug.log [version 2.0.1.0]
Tell me what happend [what page were you on]
This is all I will need

**Comment by GodLesZ** [comment]
Github created an automatic information bubble on top of the issues form, if you create a **CONTRIBUTING.md** just like the **README.md**.
This should contain such infos.

For further informations please look on these guidelines: https://github.com/blog/1184-contributing-guidelines
