### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by BraveStarr1** [eddy5641/LegendaryClient#52]
hi
how to run the legendary client?

i downloaded this .zip https://github.com/eddy5641/LegendaryClient/releases/tag/2.0.1.0
http://i39.servimg.com/u/f39/17/68/53/27/sin_ta10.png

**Comment by GodLesZ** [comment]
This is not pre-compiled release but rathe rjust a zip of a defined code state.
You have to open the **LegendaryClient.sln** solution file using Visual Studio, SharpDevelop or any other .NET IDE and compile the client by urself.

**Comment by eddy5641** [comment]
If you want a precompiled version download the zip here:
https://github.com/eddy5641/LegendaryClient/releases/tag/2.0.0.0

**Comment by rftiiv15** [comment]
Why does the source file always containg missing assemblies, random png files and stuff?  Any insight into this?  It's annoying not having all the required assemblies to compile.....

**Comment by eddy5641** [comment]
I have a older version of visual studio, and I need to update it to fix some git bugs [files that are renamed get deleted and never pushed again (example of this is TeamBuilderPage.xaml and TeamBuilderPage.xaml.cs)]

**Comment by rftiiv15** [comment]
Any idea why I'm getting an error with saying .targets properties file is invalid? It is referencing something with .net, can't remember off the back of my head as I am away from my PC.

**Comment by eddy5641** [comment]
I'm not sure. You will have to send me the file, or show the error. Currently it is past 12, and I am trying to fix bugs

**Comment by princessGasmask** [comment]
I would use precompiled, but it crashes whenever I enter a game.

**Comment by eddy5641** [comment]
Are you doing draft/ranked?

**Comment by princessGasmask** [comment]
No, it crashes in Normals for me.

**Comment by eddy5641** [comment]
New crashing when play button is hit. Compile this version by yourself to fix it
