### ISSUE TITLE
File 1.0.1.2.zip

### ISSUE THREAD

**Issue by Miloune** [eddy5641/LegendaryClient#53]
Hello,

When i try to compile the Patcher, i have an error on this line : 
Stream inStream = File.OpenRead(Path.Combine("temp", "1.0.1.2.zip"));

What is this zip file ? where i can build it ? or found it ?
Thanks

**Comment by eddy5641** [comment]
LegendaryClient will download this file on an update.
Do not set patcher as your startup project, it should be legendaryclient
