### ISSUE TITLE
using PVPNetConnect.RiotObjects.Platform.Gameinvite.Member;

### ISSUE THREAD

**Issue by rftiiv15** [eddy5641/LegendaryClient#55]
Missing reference?  Wrong dll? I DUNNO WHY THIS DOES NOT WORK PROPERLY.  can you please upload a truly 100% working push of your master file??

**Comment by eddy5641** [comment]
Visual studio sometimes excludes files that I rename. This file should contain this:

[delete the missing Member Reference, and create a new class then paste this in]

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PVPNetConnect.RiotObjects.Platform.Gameinvite.Member
{
    public class Member : RiotGamesObject
    {
        public override string TypeName
        {
            get { return this.type; }
        }

```
    private string type = "com.riotgames.platform.gameinvite.contract.Member";

    public Member()
    {
    }

    public Member(Callback callback)
    {
        this.callback = callback;
    }

    public Member(TypedObject result)
    {
        base.SetFields(this, result);
    }

    public delegate void Callback(Member result);

    private Callback callback;

    public override void DoCallback(TypedObject result)
    {
        base.SetFields(this, result);
        callback(this);
    }

    [InternalName("hasDelegatedInvitePower")]
    public bool hasDelegatedInvitePower { get; set; }

    [InternalName("summonerName")]
    public String SummonerName { get; set; }

    [InternalName("summonerId")]
    public Double SummonerId { get; set; }
}
```

}

**Comment by eddy5641** [comment]
Added
