### ISSUE TITLE
Missing files in the latest Rev (TeamControl.xaml and TeamBuilderPage.xaml)

### ISSUE THREAD

**Issue by ResQue1980** [eddy5641/LegendaryClient#57]
'Controls\TeamControl.xaml' cannot be found.
'Windows\TeamBuilderPage.xaml' cannot be found.

**Comment by eddy5641** [comment]
Added TeamBuilderPage
Will add TeamControl

**Comment by ResQue1980** [comment]
thanks for the hard work eddy :+1:

**Comment by eddy5641** [comment]
Added
