### ISSUE TITLE
Small bug in version check

### ISSUE THREAD

**Issue by ResQue1980** [eddy5641/LegendaryClient#58]
on the PatcherPage.xaml.cs page a client version number is downloaded and checked by a series of if statements.
At line 399 and line 402 a string/text file is downloaded with a line ending char \n in them. But the check at line 425 does not remove it and the check fails. Maybe we should remove all white space and line endings before the check or reformat the remote files.

line 399: var version = new WebClient().DownloadString("http://eddy5641.github.io/LegendaryClient/Version");
line 402: var versiontoint = new WebClient().DownloadString("http://eddy5641.github.io/LegendaryClient/VersionAsInt");
//This will fail because: "2.0.0.0" == "2.0.0.0\n"
line 425: else if (Client.LegendaryClientVersion == version)

**Comment by eddy5641** [comment]
I have a temporary solution, that uses just the integers then converts the string to an int on that versionasint. In the future though, I will use a string split

**Comment by eddy5641** [comment]
This will be the new code

string LatestLCVersion = new WebClient().DownloadString("http://eddy5641.github.io/LegendaryClient/VersionAsInt");

string[] ProperLCVersion = LatestLCVersion.Split(new string[] { Environment.NewLine }, StringSplitOptions.None);
if (Client.LegendaryClientVersion == ProperLCVersion)

**Comment by Dispersia** [comment]
This isn't a thing anymore.
