### ISSUE TITLE
RtmpsLegendaryClient

### ISSUE THREAD

**Issue by eddy5641** [eddy5641/LegendaryClient#6]
https://github.com/eddy5641/RtmpsLegendaryClient
This is going to be my second LegendaryClient using rtmp-sharp instead of pvpnetconnect
Disclamer, I have never used rtmp-sharp

**Comment by kevvv** [comment]
So that means you're going to move on over to that other one and this one is going to go inactive right?

**Comment by eddy5641** [comment]
partially, just the rtmp one will be easier to work with

**Comment by eddy5641** [comment]
Its more like a future movement, to make dev easier
