### ISSUE TITLE
Stuff that is crashing it LIST

### ISSUE THREAD

**Issue by ar1a** [eddy5641/LegendaryClient#61]
1. Clicking spectate
2. Team queue
3. Getting ingame

**Comment by eddy5641** [comment]
Using a precompiled version will cause crashing. The next release should have these issues fixed

**Comment by ar1a** [comment]
I compiled 2.0.1.0

**Comment by ar1a** [comment]
Ok i compiled the current github and i have to say its rather functional, and a well done to you.
You are probably aware, but recieving a game invite, causes you to crash.
Furhuremore you cannot add bots to games which is rather annoying.

**Comment by eddy5641** [comment]
If you spectate, The client will not start right, but you should not crash when receiving a game invite. Are you sure you are using Master? https://github.com/eddy5641/LegendaryClient/archive/master.zip

**Comment by ar1a** [comment]
Yes im sure, i was running via VS which may cause some exceptions to be thrown.
Do you have a skype i can contact btw?

**Comment by eddy5641** [comment]
eddydavinchi [ed vo]

**Comment by ar1a** [comment]
Added, im iSnorflake

**Comment by eddy5641** [comment]
Wait. You might crash if it is for ranked. I have only tested normals
