### ISSUE TITLE
LAN server

### ISSUE THREAD

**Issue by BraveStarr1** [eddy5641/LegendaryClient#62]
how to play in LAN server with legendary client?

get only LAS server

help me please :(

**Comment by eddy5641** [comment]
C:\Riot Games\League of Legends\RADS\projects\lol_air_client\releases\0.0.1.105\deploy
lol.properties
Send this file

**Comment by BraveStarr1** [comment]
https://www.mediafire.com/?spt0jpff4rfbmac
