### ISSUE TITLE
Crashed by the new release LegendaryClient

### ISSUE THREAD

**Issue by SilverHand0** [eddy5641/LegendaryClient#64]
Hi, I just download the new release LegendaryClient in https://github.com/eddy5641/LegendaryClient/releases .

But, when I start the client I got a instant crash.

I can see the log "starting Patcher..." and then got a crashed.

The previous version is starting successfully, but It said "[5:21 AM] Checking if League of Legends is Up-To-Date
[5:21 AM] League of Legends is not Up-To-Date. Please Update League Of Legends"  even my LoL client is latest. 

I'm so glad you if you leave a comment sir. 

Thanks for reading. I hope I can use the Legendary Client.

**Comment by SilverHand0** [comment]
Okay, I think that was one of my desktop problem. I tried to use LegendaryClient on my laptop. Now I can open "LegendaryClient.exe", but another problem comes out.

During "extracting DataDragon" like 40%, I got a crash. :( 

Do I need manually to install something ?

**Comment by eddy5641** [comment]
Send me the LegendaryClient.log file

**Comment by SilverHand0** [comment]
K, I just sent log file to your Gmail. Check it.

**Comment by eddy5641** [comment]
(9/11/2014 11:36 AM) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown

(9/11/2014 11:36 AM) [UNHANDLEDEXCEPTION]: The remote server returned an error: (404) Not Found.

(9/11/2014 11:36 AM) [UNHANDLEDEXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at System.Net.WebClient.DownloadString(String address)
   at LegendaryClient.Windows.PatcherPage.<StartPatcher>b__0() in c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\PatcherPage.xaml.cs:line 531
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

Exact line of code:
string Release = UpdateClient.DownloadString("http://l3cdn.riotgames.com/releases/live/projects/lol_air_client/releases/releaselisting_NA");

Swiched to:
string Release = UpdateClient.DownloadString("http://l3cdn.riotgames.com/releases/live/projects/lol_air_client/releases/releaselisting");

**Comment by eddy5641** [comment]
Try going to this link: "http://l3cdn.riotgames.com/releases/live/projects/lol_air_client/releases/releaselisting"

**Comment by SilverHand0** [comment]
I'm not at home now, I'll try later. Thx for helping.

**Comment by SilverHand0** [comment]
Okay, I had fixed that problem. :D 

But, I have an another problem, when I try to login on NA server. It says "Unable to get Auth Key"

Pic : http://i.imgur.com/w4TJmuu.jpg

I sent a log file to your email again.

**Comment by eddy5641** [comment]
Sometimes you have to restart or re-login to legendaryclient because it does not try to login 3 times [server lag things]

**Comment by SilverHand0** [comment]
Oh, yeah. I got it. That's was my problem.

And is Spectate feature available now?

Cuz, I can't use that feature, it causes crash :(

**Comment by eddy5641** [comment]
use
internal static void LaunchSpectatorGame(string SpectatorServer, string Key,
int GameId, string Platform) { string GameDirectory = GetGameDirectory();
var p = new System.Diagnostics.Process(); p.StartInfo.WorkingDirectory =
GameDirectory; p.StartInfo.FileName = Path.Combine(GameDirectory, "League
of Legends.exe"); //p.StartInfo.FileName = Location;
p.StartInfo.Arguments = "\"8394\"
\"" + RootLocation + "LoLLauncher.exe" \"\" \"spectator " + SpectatorServer
- " " + Key + " " + GameId + " " + Platform + "\""; p.Start(); }
