### ISSUE TITLE
Friend creating ranked

### ISSUE THREAD

**Issue by nairaner** [eddy5641/LegendaryClient#68]
If someone creates ranked queue then in friends it says that he's "in game as Shyvana"

Also the last ping address (95.172.65.1) is european server and is disabled for EUNE.

**Comment by eddy5641** [comment]
Usually when any player is creating a queue then it says in game as Shyvana
Will add ping address (have been working on a different repo, this is still active)

**Comment by horato** [comment]
Status text fixed in 60081a98b6a33f0b8880c8844987004d89b809cb
As for the ping, it works for me (eune).

**Comment by Dispersia** [comment]
if you fix it feel free to close ;)
