### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by eddy5641** [eddy5641/LegendaryClient#69]
I am aware that LegendaryClient crashes on start. This is a json error and will be fixed as soon as possible

**Comment by maxiking913** [comment]
Fix PLSSSSSSSSSS, i wanna play with this client again :)1

**Comment by maxiking913** [comment]
Btw what is with legacy pvp?

**Comment by eddy5641** [comment]
Legacy PVP is currently not receiving pushs, I am going to do one GIGANTIC push that should work right away (with some bugs and no teambuilder)

**Comment by maxiking913** [comment]
Will you Stop work on Legendary Client when you do the GIGANTIC push ^^? and will it include all features from Legendary Client too:)?

**Comment by eddy5641** [comment]
LegenadryClient will still be continued. LegacyPVP will just be a different ui for users to use. It will have more winterminty features too (Replays)

**Comment by maxiking913** [comment]
Okay, how long did u need to fix the legendary starting client?

**Comment by eddy5641** [comment]
Probably 1 hour today
I haven't been having a lot of time to program this week
I need to switch the json stuff

**Comment by maxiking913** [comment]
Okay, this is nice ^^ thanks for ur information

**Comment by eddy5641** [comment]
Found crashing thanks to Kogmaw

**Comment by maxiking913** [comment]
Just getting error when i try to compile.

**Comment by eddy5641** [comment]
What is the error 
(Did you clone with this link? https://github.com/eddy5641/LegendaryClient.git)

**Comment by maxiking913** [comment]
yes i downloadet as zip
