### ISSUE TITLE
Crash after clicking Play

### ISSUE THREAD

**Issue by eco999** [eddy5641/LegendaryClient#70]
The game crashes after clicking Play. This is the latest version on the LCInstaller. Here is the log. It says something like LegendaryClient is out of date. I have the version 2.0.1.0-LogUpdate. http://pastebin.com/UvM9RU22

**Comment by maxiking913** [comment]
its fixed i think. just compile yourself

**Comment by eddy5641** [comment]
Fixed already and stated in #69 If you get errors with compiling use the clone feature (in visual studio)

**Comment by maxiking913** [comment]
Die Komponente "rtmp-sharp", auf die verwiesen wird, wurde nicht gefunden.  LegendaryClient

its my error.

In english:

he cant found "rtmp-sharp"

**Comment by maxiking913** [comment]
Pls Compile for us. i dont get it. idk if im silly. used clone via vs 2013. not working still same errors. :(

**Comment by eddy5641** [comment]
compile this file here:
https://github.com/astralfoxy/rtmp-sharp
Disable code signing in the settings and add it as a reference

**Comment by maxiking913** [comment]
Got it thanks. :) Nice work
