### ISSUE TITLE
Using LCLient AutoInstaller

### ISSUE THREAD

**Issue by princessGasmask** [eddy5641/LegendaryClient#71]
gets past "extracting datadragon." as soon as "checking adobe air version", the client crashes immediately. using version 2.0.1.0. also tried the two updated versions, log and crash. the last one will not open period and the log version only will open and crash immediately.

**Comment by eddy5641** [comment]
Can you send me the Log file?

**Comment by eddy5641** [comment]
start legendaryClient from this location:
C:\LegenadryClient\Client
