### ISSUE TITLE
Crashes immediately after clicking play

### ISSUE THREAD

**Issue by Silhrian** [eddy5641/LegendaryClient#72]
https://gist.github.com/Silhrian/1dcc8412d622dfcb7f7d 

That's the log, I've tried everything literally and still can't get it to work.

**Comment by Silhrian** [comment]
Apparently it's fixed by compiling the source yourself well I can't do that cause I keep getting 3 errors.

http://i.imgur.com/ivG2vU5.png

**Comment by Silhrian** [comment]
Compiled it and it works fine there is just 1 error in the logs - should I be bothered by it?

(10/7/2014 3:33 AM) [EXCEPTION]: A first chance exception was thrown
(10/7/2014 3:33 AM) [EXCEPTION]: Application identity is not set.
(10/7/2014 3:33 AM) [EXCEPTION]:    at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
(10/7/2014 3:33 AM) [EXCEPTION]: A first chance exception was thrown
(10/7/2014 3:33 AM) [EXCEPTION]: The given key was not present in the dictionary.
(10/7/2014 3:33 AM) [EXCEPTION]:    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
(10/7/2014 3:35 AM) [EXCEPTION]: A first chance exception was thrown
(10/7/2014 3:35 AM) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(10/7/2014 3:35 AM) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)

**Comment by princessGasmask** [comment]
How did you fix the errors, I'm getting them now.

**Comment by Silhrian** [comment]
create an empty LegendaryClientDownloadLogic.cs, rename DownloadAir and DownloadEverything to anything you'd like and change the DownloadAir to whatever you named it in one more file, I forgot which one already

**Comment by princessGasmask** [comment]
This is what I ended up with. http://i.imgur.com/gnerKzp.png
It's progress. However, the patcher stays at zero and doesn't actually do anything.

EDIT: Got everything running. Thank you. :+1:

**Comment by Silhrian** [comment]
Are you running LegendaryClient.exe? It doesn't seem like it at all.

EDIT: You're welcome.

**Comment by eddy5641** [comment]
LegendaryClient.Patcher Is a work in progress. Thank you Silhrian, for helping users out, I do not have all the time to do that :)
The future patcher will download League Of Legends meaning that you will not need the LOL install anymore
