### ISSUE TITLE
LegendaryClient has stopped working

### ISSUE THREAD

**Issue by Miloune** [eddy5641/LegendaryClient#73]
Hey,

I wanted to trying your LegendaryClient, i downloaded your last Release : https://github.com/eddy5641/LegendaryClient/releases/download/2.0.1.0-LogUpdate/Client.zip

But when i click on "Play", i got a popup "LegendaryClient has stopped working"

Here my Log file : 
 (07/10/2014 12:41) [LOG]: LegendaryClient Started Up Successfully
(07/10/2014 12:41) [LOG]: Starting Patcher
(07/10/2014 12:41) [LOG]: MD5: EFD0DD429FB9C4046736539BD2893EBE
(07/10/2014 12:41) [LOG]: Most Up to date LegendaryClient Version: 2.0.0.0

(07/10/2014 12:41) [LOG]: LegendaryClient Is Out of Date!
(07/10/2014 12:41) [LOG]: DataDragon Version: 4.17.1
(07/10/2014 12:41) [LOG]: Current DataDragon Version: 4.17.1
(07/10/2014 12:41) [LOG]: DDragon Version (LOL Version) = 4.17.1
(07/10/2014 12:41) [LOG]: Client Version: 4.17.1
(07/10/2014 12:41) [EXCEPTION]: A first chance exception was thrown
(07/10/2014 12:41) [EXCEPTION]: Le nom d'une clé de Registre doit commencer par un nom de clé de base valide.
(07/10/2014 12:41) [EXCEPTION]:    à Microsoft.Win32.Registry.GetBaseKeyFromKeyName(String keyName, String& subKeyName)
(07/10/2014 12:41) [EXCEPTION]: A first chance exception was thrown
(07/10/2014 12:41) [EXCEPTION]: Le nom d'une clé de Registre doit commencer par un nom de clé de base valide.
(07/10/2014 12:41) [EXCEPTION]:    à Microsoft.Win32.Registry.GetBaseKeyFromKeyName(String keyName, String& subKeyName)
(07/10/2014 12:41) [EXCEPTION]: A first chance exception was thrown
(07/10/2014 12:41) [EXCEPTION]: Le nom d'une clé de Registre doit commencer par un nom de clé de base valide.
(07/10/2014 12:41) [EXCEPTION]:    à Microsoft.Win32.Registry.GetBaseKeyFromKeyName(String keyName, String& subKeyName)
(07/10/2014 12:41) [EXCEPTION]: A first chance exception was thrown
(07/10/2014 12:41) [EXCEPTION]: Le nom d'une clé de Registre doit commencer par un nom de clé de base valide.
(07/10/2014 12:41) [EXCEPTION]:    à Microsoft.Win32.Registry.GetBaseKeyFromKeyName(String keyName, String& subKeyName)
(07/10/2014 12:41) [LOG]: Air Assets Version: 0.0.1.112
(07/10/2014 12:41) [LOG]: Current Air Assets Version: 0.0.1.112
(07/10/2014 12:41) [LOG]: Trying to detect League of Legends GameClient
(07/10/2014 12:41) [LOG]: League of Legends is located at: C:\Riot Games\League of Legends\
(07/10/2014 12:41) [LOG]: Latest League of Legends GameClient: 0.0.1.58
(07/10/2014 12:41) [LOG]: Checking if League of Legends is Up-To-Date
(07/10/2014 12:41) [LOG]: League of Legends is Up-To-Date
(07/10/2014 12:41) [LOG]: League Of Legends Version: 0.0.0.253
(07/10/2014 12:41) [LOG]: Current League of Legends Version: 0.0.0.0
(07/10/2014 12:41) [LOG]: Checking for existing League of Legends Installation
(07/10/2014 12:41) [LOG]: Getting League Of Legends from C:\Riot Games\League of Legends\RADS
(07/10/2014 12:41) [LOG]: Retrieved currently installed League of Legends
(07/10/2014 12:41) [LOG]: Current League of Legends Version: C:\Riot Games\League of Legends\RADS
(07/10/2014 12:41) [LOG]: LegendaryClient Has Finished Patching
(07/10/2014 12:41) [LOG]: LegendaryClient Has Finished Patching
(07/10/2014 12:41) [EXCEPTION]: A first chance exception was thrown
(07/10/2014 12:41) [EXCEPTION]: La clé donnée était absente du dictionnaire.
(07/10/2014 12:41) [EXCEPTION]:    à System.Collections.Generic.Dictionary`2.get_Item(TKey key)
(07/10/2014 12:41) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(07/10/2014 12:41) [UNHANDLEDEXCEPTION]: La clé donnée était absente du dictionnaire.
(07/10/2014 12:41) [UNHANDLEDEXCEPTION]:    à System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   à LegendaryClient.Logic.JSON.Champions.InsertExtraChampData(champions Champ) dans c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Logic\JSON\Champions.cs:ligne 22
   à LegendaryClient.Windows.LoginPage..ctor() dans c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\LoginPage.xaml.cs:ligne 61
   à LegendaryClient.Windows.PatcherPage.SkipPatchButton_Click(Object sender, RoutedEventArgs e) dans c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\PatcherPage.xaml.cs:ligne 347
   à System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   à System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   à System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   à System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
   à System.Windows.Controls.Primitives.ButtonBase.OnClick()
   à System.Windows.Controls.Button.OnClick()
   à System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   à System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
   à System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   à System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   à System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   à System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   à System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   à System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   à System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
   à System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   à System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   à System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   à System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   à System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   à System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
   à System.Windows.Input.InputManager.ProcessStagingArea()
   à System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   à System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   à System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   à System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   à MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   à System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   à MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   à System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   à MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   à MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   à System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   à System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   à System.Windows.Threading.Dispatcher.Run()
   à System.Windows.Application.RunDispatcher(Object ignore)
   à System.Windows.Application.RunInternal(Window window)
   à System.Windows.Application.Run(Window window)
   à LegendaryClient.App.Main() dans c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\obj\Release\App.g.cs:ligne 0

When i check the VERSION_LOL file in RADS folder it's write "0.0.0.0", is that normal ?

PS : Sorry for my bad english

**Comment by ghost** [comment]
The last release is not up-to-date, you need to download the source and compile it.

**Comment by Miloune** [comment]
I downloaded the last version, and now i get this : 

(08/10/2014 12:55) [LOG]: LegendaryClient Started Up Successfully
(08/10/2014 12:55) [LOG]: Starting Patcher
(08/10/2014 12:55) [LOG]: DataDragon Version: 4.17.1
(08/10/2014 12:55) [LOG]: Current DataDragon Version: 4.17.1
(08/10/2014 12:55) [LOG]: DDragon Version (LOL Version) = 4.17.1
(08/10/2014 12:55) [LOG]: Client Version: 4.17.1
(08/10/2014 12:55) [EXCEPTION]: A first chance exception was thrown
(08/10/2014 12:55) [EXCEPTION]: Le nom d'une clé de Registre doit commencer par un nom de clé de base valide.
(08/10/2014 12:55) [EXCEPTION]:    à Microsoft.Win32.Registry.GetBaseKeyFromKeyName(String keyName, String& subKeyName)
(08/10/2014 12:55) [EXCEPTION]: A first chance exception was thrown
(08/10/2014 12:55) [EXCEPTION]: Le nom d'une clé de Registre doit commencer par un nom de clé de base valide.
(08/10/2014 12:55) [EXCEPTION]:    à Microsoft.Win32.Registry.GetBaseKeyFromKeyName(String keyName, String& subKeyName)
(08/10/2014 12:55) [EXCEPTION]: A first chance exception was thrown
(08/10/2014 12:55) [EXCEPTION]: Le nom d'une clé de Registre doit commencer par un nom de clé de base valide.
(08/10/2014 12:55) [EXCEPTION]:    à Microsoft.Win32.Registry.GetBaseKeyFromKeyName(String keyName, String& subKeyName)
(08/10/2014 12:55) [EXCEPTION]: A first chance exception was thrown
(08/10/2014 12:55) [EXCEPTION]: Le nom d'une clé de Registre doit commencer par un nom de clé de base valide.
(08/10/2014 12:55) [EXCEPTION]:    à Microsoft.Win32.Registry.GetBaseKeyFromKeyName(String keyName, String& subKeyName)
(08/10/2014 12:55) [LOG]: Air Assets Version: 0.0.1.112
(08/10/2014 12:55) [LOG]: Current Air Assets Version: 0.0.1.112
(08/10/2014 12:55) [EXCEPTION]: A first chance exception was thrown
(08/10/2014 12:55) [EXCEPTION]: Le serveur distant a retourné une erreur : (404) Introuvable.
(08/10/2014 12:55) [EXCEPTION]:    à System.Net.HttpWebRequest.GetResponse()
(08/10/2014 12:55) [EXCEPTION]: A first chance exception was thrown
(08/10/2014 12:55) [EXCEPTION]: Le serveur distant a retourné une erreur : (404) Introuvable.
(08/10/2014 12:55) [EXCEPTION]:    à System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(08/10/2014 12:55) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(08/10/2014 12:55) [UNHANDLEDEXCEPTION]: Le serveur distant a retourné une erreur : (404) Introuvable.
(08/10/2014 12:55) [UNHANDLEDEXCEPTION]:    à System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   à System.Net.WebClient.DownloadString(Uri address)
   à System.Net.WebClient.DownloadString(String address)
   à LegendaryClient.Windows.PatcherPage.<StartPatcher>b__0() dans c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\PatcherPage.xaml.cs:ligne 217
   à System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart()

**Comment by Miloune** [comment]
Got the same problem than https://github.com/eddy5641/LegendaryClient/issues/75
and with the last riot update, the patcher work well.
