### ISSUE TITLE
The given key was not present in the dictionary.

### ISSUE THREAD

**Issue by princessGasmask** [eddy5641/LegendaryClient#76]
After new patch, I get this every time I try to login, despite the LegendaryClient stating that everything is up to date.

**Comment by nairaner** [comment]
on login screen change 4.17.1 to 4.18.1

**Comment by Dispersia** [comment]
Riot doesn't update DDragon the second they release a patch (for whatever reason). As nairaner said, simply change it - a lot of icons (especially abilities) got renamed however, so you will notice a few missing icons for now.

**Comment by princessGasmask** [comment]
Thank you
