### ISSUE TITLE
Sometimes, joining queues does not work.

### ISSUE THREAD

**Issue by princessGasmask** [eddy5641/LegendaryClient#78]
Sometimes, when pressing "Join Queue" on normal 5v5 (not draft), the timer will display 0:00, before changing back to "Join Queue." I try several more times, getting the same result. I logout, then log back in when I get this error.
![capture](https://cloud.githubusercontent.com/assets/5853862/4599657/0f16af4e-50c9-11e4-94f6-e3c4b9ccc3eb.PNG)

**Comment by eddy5641** [comment]
try restaring the client

**Comment by eddy5641** [comment]
that error is a jabber-net error

**Comment by Dispersia** [comment]
This was error handled but there is no real way to fix if the riot servers are messing up.
