### ISSUE TITLE
ARAM bug

### ISSUE THREAD

**Issue by nairaner** [eddy5641/LegendaryClient#82]
Cant see my team, only enemies
I was purple side
http://puu.sh/cjyrT/06c4f29fde.jpg

**Comment by Dispersia** [comment]
I made several games and couldn't recreate the issue. What server and through solo or team queue? Is it every time or just this one?

**Comment by nairaner** [comment]
I was solo and it happened in the only ARAM i played. EUNE

**Comment by Dispersia** [comment]
I will have to try it in that region but I don't see why it would be different. Tried ~20 games now and not a single one that happened to, so hard to debug lol.

**Comment by eddy5641** [comment]
Does this still occur? If it does, can you send a log?

**Comment by nairaner** [comment]
There was nothing interesting in log, when it happened and it happened to me only once.

**Comment by nairaner** [comment]
so this happened again, so random
