### ISSUE TITLE
Replays

### ISSUE THREAD

**Issue by juaoose** [eddy5641/LegendaryClient#89]
After getting all the chunks, the client stops working. After this crash, whenever you try to go into replays tab, it will crash again and again.

The logs say something like this:
[EXCEPTION]: No se puede convertir un objeto de tipo 'RtmpSharp.IO.AsObject' al tipo 'PVPNetConnect.RiotObjects.Platform.Statistics.EndOfGameStats'.
(27/10/2014 11:38 p. m.) [EXCEPTION]:    en LegendaryClient.Windows.ReplayPage.UpdateReplays()
(27/10/2014 11:38 p. m.) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(27/10/2014 11:38 p. m.) [UNHANDLEDEXCEPTION]: No se puede convertir un objeto de tipo 'RtmpSharp.IO.AsObject' al tipo 'PVPNetConnect.RiotObjects.Platform.Statistics.EndOfGameStats'.
(27/10/2014 11:38 p. m.) [UNHANDLEDEXCEPTION]:    en LegendaryClient.Windows.ReplayPage.UpdateReplays()

Which in english is something like there is an exception trying to convert a RtmpSharp.IO.AsObject to a PVPNetConnect.RiotObject.Platform...

**Comment by eddy5641** [comment]
It can not convert PVPNetConnect.RiotObjects.Platform.Statistics.EndOfGameStats into RtmpSharp.IO.AsObject (fails to because they are different dlls with different formats)
Corrected

**Comment by eddy5641** [comment]
Fixed in release that will come out today

**Comment by Zer0code** [comment]
Where are the new releases available, if I may ask?

**Comment by eddy5641** [comment]
Can be found here: https://github.com/eddy5641/LegendaryClient/releases
I am working on a quick patcher that will patch LC when launched

**Comment by Zer0code** [comment]
Ok thy! :))
