### ISSUE TITLE
Party problems

### ISSUE THREAD

**Issue by Lolr** [eddy5641/LegendaryClient#91]
When you get invited to a party it doesn't show the people in the pre-made team lobby before you queue up. Also once it finds a match that screen is completely bugged and crashes the game.

(28/10/2014 14:42) [LOG]: LegendaryClient Has Finished Patching
(28/10/2014 14:42) [LOG]: LegendaryClient Started Up Successfully
(28/10/2014 14:42) [LOG]: Starting Patcher
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: Could not load file or assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.
(28/10/2014 14:42) [EXCEPTION]:    at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(28/10/2014 14:42) [LOG]: DataDragon Version: 4.18.1
(28/10/2014 14:42) [LOG]: Current DataDragon Version: 4.18.1
(28/10/2014 14:42) [LOG]: DDragon Version (LOL Version) = 4.18.1
(28/10/2014 14:42) [LOG]: Client Version: 4.18.1
(28/10/2014 14:42) [LOG]: Air Assets Version: 0.0.1.115
(28/10/2014 14:42) [LOG]: Current Air Assets Version: 0.0.1.115
(28/10/2014 14:42) [LOG]: Trying to detect League of Legends GameClient
(28/10/2014 14:42) [LOG]: League of Legends is located at: C:\Riot Games\League of Legends\
(28/10/2014 14:42) [LOG]: Latest League of Legends GameClient: 0.0.1.62
(28/10/2014 14:42) [LOG]: Checking if League of Legends is Up-To-Date
(28/10/2014 14:42) [LOG]: League of Legends is Up-To-Date
(28/10/2014 14:42) [LOG]: LegendaryClient Has Finished Patching
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:42) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:42) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:42) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:42) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:42) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:42) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:42) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:42) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: An invalid IP address was specified.
(28/10/2014 14:42) [EXCEPTION]:    at System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(28/10/2014 14:42) [LOG]: Connected and logged in asMrBelgio
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: Application identity is not set.
(28/10/2014 14:42) [EXCEPTION]:    at System.Deployment.Application.ApplicationDeployment.get_CurrentDeployment()
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:42) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:42) [EXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: Cannot locate resource 'dev.png'.
(28/10/2014 14:42) [EXCEPTION]:    at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: Cannot locate resource 'dev.png'.
(28/10/2014 14:42) [EXCEPTION]:    at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: Cannot locate resource 'dev.png'.
(28/10/2014 14:42) [EXCEPTION]:    at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: Cannot locate resource 'dev.png'.
(28/10/2014 14:42) [EXCEPTION]:    at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: Cannot locate resource 'dev.png'.
(28/10/2014 14:42) [EXCEPTION]:    at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: Cannot locate resource 'dev.png'.
(28/10/2014 14:42) [EXCEPTION]:    at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: Cannot locate resource 'dev.png'.
(28/10/2014 14:42) [EXCEPTION]:    at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: Cannot locate resource 'dev.png'.
(28/10/2014 14:42) [EXCEPTION]:    at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
(28/10/2014 14:42) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:42) [EXCEPTION]: Cannot locate resource 'dev.png'.
(28/10/2014 14:42) [EXCEPTION]:    at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
(28/10/2014 14:43) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:43) [EXCEPTION]: Cannot locate resource 'dev.png'.
(28/10/2014 14:43) [EXCEPTION]:    at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
(28/10/2014 14:43) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:43) [EXCEPTION]: Cannot locate resource 'dev.png'.
(28/10/2014 14:43) [EXCEPTION]:    at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
(28/10/2014 14:43) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:43) [EXCEPTION]: Cannot locate resource 'dev.png'.
(28/10/2014 14:43) [EXCEPTION]:    at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
(28/10/2014 14:43) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:43) [EXCEPTION]: Cannot locate resource 'dev.png'.
(28/10/2014 14:43) [EXCEPTION]:    at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
(28/10/2014 14:43) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:43) [EXCEPTION]: Cannot locate resource 'dev.png'.
(28/10/2014 14:43) [EXCEPTION]:    at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
(28/10/2014 14:43) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:43) [EXCEPTION]: Cannot locate resource 'dev.png'.
(28/10/2014 14:43) [EXCEPTION]:    at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
(28/10/2014 14:43) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:43) [EXCEPTION]: Unable to cast object of type 'PVPNetConnect.TypedObject' to type 'System.Object[]'.
(28/10/2014 14:43) [EXCEPTION]:    at PVPNetConnect.TypedObject.GetArray(String key)
(28/10/2014 14:43) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:43) [EXCEPTION]: The given key was not present in the dictionary.
(28/10/2014 14:43) [EXCEPTION]:    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
(28/10/2014 14:43) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:43) [EXCEPTION]: The given key was not present in the dictionary.
(28/10/2014 14:43) [EXCEPTION]:    at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
(28/10/2014 14:43) [LOG]: Failed to join room.
(28/10/2014 14:43) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:43) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:43) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(28/10/2014 14:43) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:43) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:43) [EXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(28/10/2014 14:43) [LOG]: Failed to join room.
(28/10/2014 14:43) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:43) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:43) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(28/10/2014 14:43) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:43) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:43) [EXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(28/10/2014 14:43) [LOG]: Failed to join room.
(28/10/2014 14:43) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:43) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:43) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(28/10/2014 14:43) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:43) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:43) [EXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(28/10/2014 14:43) [LOG]: Failed to join room.
(28/10/2014 14:43) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:43) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:43) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(28/10/2014 14:43) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:43) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:43) [EXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(28/10/2014 14:44) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:44) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:44) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(28/10/2014 14:44) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:44) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:44) [EXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(28/10/2014 14:44) [LOG]: Failed to join room.
(28/10/2014 14:44) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:44) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:44) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(28/10/2014 14:44) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:44) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:44) [EXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(28/10/2014 14:44) [LOG]: Failed to join room.
(28/10/2014 14:44) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:44) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:44) [EXCEPTION]:    at System.Net.HttpWebRequest.GetResponse()
(28/10/2014 14:44) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:44) [EXCEPTION]: The remote server returned an error: (404) Not Found.
(28/10/2014 14:44) [EXCEPTION]:    at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(28/10/2014 14:44) [LOG]: Preforming LCDSHeartBeat
(28/10/2014 14:44) [LOG]: Preforming LCDSHeartBeat
(28/10/2014 14:44) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:44) [EXCEPTION]: Cannot locate resource 'dev.png'.
(28/10/2014 14:44) [EXCEPTION]:    at MS.Internal.AppModel.ResourcePart.GetStreamCore(FileMode mode, FileAccess access)
(28/10/2014 14:44) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:44) [EXCEPTION]: Collection was modified; enumeration operation may not execute.
(28/10/2014 14:44) [EXCEPTION]:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
(28/10/2014 14:44) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:44) [EXCEPTION]: Collection was modified; enumeration operation may not execute.
(28/10/2014 14:44) [EXCEPTION]:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
(28/10/2014 14:44) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:44) [EXCEPTION]: Collection was modified; enumeration operation may not execute.
(28/10/2014 14:44) [EXCEPTION]:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
(28/10/2014 14:44) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:44) [EXCEPTION]: Collection was modified; enumeration operation may not execute.
(28/10/2014 14:44) [EXCEPTION]:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
(28/10/2014 14:44) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:44) [EXCEPTION]: Collection was modified; enumeration operation may not execute.
(28/10/2014 14:44) [EXCEPTION]:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
(28/10/2014 14:44) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:44) [EXCEPTION]: Collection was modified; enumeration operation may not execute.
(28/10/2014 14:44) [EXCEPTION]:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
(28/10/2014 14:44) [EXCEPTION]: A first chance exception was thrown
(28/10/2014 14:44) [EXCEPTION]: Collection was modified; enumeration operation may not execute.
(28/10/2014 14:44) [EXCEPTION]:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at LegendaryClient.Windows.QueuePopOverlay.<InitializePop>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
(28/10/2014 14:44) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(28/10/2014 14:44) [UNHANDLEDEXCEPTION]: Collection was modified; enumeration operation may not execute.
(28/10/2014 14:44) [UNHANDLEDEXCEPTION]:    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at LegendaryClient.Windows.QueuePopOverlay.<InitializePop>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.Run()
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at LegendaryClient.App.Main()

**Comment by eddy5641** [comment]
Queue pop bug. Will fix in next patch [Coming today]
