### ISSUE TITLE
Spell icons in Champion select

### ISSUE THREAD

**Issue by nairaner** [eddy5641/LegendaryClient#94]
Need to convert to get icon file name from DDragon. Currently get file name from gamestats, which is used in Air client and different than DDragon.

**Comment by Dispersia** [comment]
DDragon just needs to be removed. Almost nothing in there is correct compared to the sqlite file. Just need to add that code to GetAllPngs from http://l3cdn.riotgames.com/releases/live/projects/lol_air_client/releases/0.0.1.115/packages/files/packagemanifest later.

**Comment by Dispersia** [comment]
Fixed as well as sorted the icons on ChampSelectPage.

NOTE: Delete everything besides the Client folder to update, it will only download if new DDragon version is released (aka, a new patch or something)
