### ISSUE TITLE
error

### ISSUE THREAD

**Issue by lessn** [eddy5641/LegendaryClient#98]
(04/11/2014 08:09) [LOG]: LegendaryClient Has Finished Patching
(04/11/2014 08:09) [LOG]: LegendaryClient Started Up Successfully
(04/11/2014 08:09) [LOG]: Starting Patcher
(04/11/2014 08:09) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:09) [EXCEPTION]: Não foi possível carregar arquivo ou assembly 'mscorlib.XmlSerializers, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' ou uma de suas dependências. O sistema não pode encontrar o arquivo especificado.
(04/11/2014 08:09) [EXCEPTION]:    em System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   em System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
(04/11/2014 08:12) [LOG]: DataDragon Version: 4.18.1
(04/11/2014 08:12) [LOG]: Current DataDragon Version: 4.18.1
(04/11/2014 08:12) [LOG]: DDragon Version (LOL Version) = 4.18.1
(04/11/2014 08:12) [LOG]: Client Version: 4.18.1
(04/11/2014 08:13) [LOG]: Air Assets Version: 0.0.1.115
(04/11/2014 08:13) [LOG]: Current Air Assets Version: 0.0.1.115
(04/11/2014 08:13) [LOG]: Trying to detect League of Legends GameClient
(04/11/2014 08:13) [LOG]: League of Legends is located at: C:\Riot Games\League of Legends\
(04/11/2014 08:13) [LOG]: Latest League of Legends GameClient: 0.0.1.62
(04/11/2014 08:13) [LOG]: Checking if League of Legends is Up-To-Date
(04/11/2014 08:13) [LOG]: League of Legends is Up-To-Date
(04/11/2014 08:13) [LOG]: LegendaryClient Has Finished Patching
(04/11/2014 08:13) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:13) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:13) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:13) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:13) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:13) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:13) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:13) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:13) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:13) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:13) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:13) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:13) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:13) [EXCEPTION]: Endereço IP inválido foi especificado.
(04/11/2014 08:13) [EXCEPTION]:    em System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(04/11/2014 08:13) [LOG]: Connected and logged in astamiresantiago
(04/11/2014 08:13) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:13) [EXCEPTION]: O servidor remoto retornou um erro: (404) Não Localizado.
(04/11/2014 08:13) [EXCEPTION]:    em System.Net.HttpWebRequest.GetResponse()
(04/11/2014 08:13) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:13) [EXCEPTION]: O servidor remoto retornou um erro: (404) Não Localizado.
(04/11/2014 08:13) [EXCEPTION]:    em System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(04/11/2014 08:15) [LOG]: Preforming LCDSHeartBeat
(04/11/2014 08:15) [LOG]: Preforming LCDSHeartBeat
(04/11/2014 08:17) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:17) [EXCEPTION]: Não é possível acessar um objeto descartado.
Nome do objeto: 'System.Net.Sockets.NetworkStream'.
(04/11/2014 08:17) [EXCEPTION]:    em System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
(04/11/2014 08:17) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:17) [EXCEPTION]: Não é possível acessar um objeto descartado.
Nome do objeto: 'SslStream'.
(04/11/2014 08:17) [EXCEPTION]:    em System.Net.Security.SslState.CheckThrow(Boolean authSucessCheck)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Endereço IP inválido foi especificado.
(04/11/2014 08:18) [EXCEPTION]:    em System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(04/11/2014 08:18) [LOG]: Connected and logged in astamiresantiago
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:18) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: O servidor remoto retornou um erro: (404) Não Localizado.
(04/11/2014 08:18) [EXCEPTION]:    em System.Net.HttpWebRequest.GetResponse()
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: O servidor remoto retornou um erro: (404) Não Localizado.
(04/11/2014 08:18) [EXCEPTION]:    em System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: Endereço IP inválido foi especificado.
(04/11/2014 08:18) [EXCEPTION]:    em System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(04/11/2014 08:18) [LOG]: Connected and logged in asathuslol
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: O servidor remoto retornou um erro: (404) Não Localizado.
(04/11/2014 08:18) [EXCEPTION]:    em System.Net.HttpWebRequest.GetResponse()
(04/11/2014 08:18) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:18) [EXCEPTION]: O servidor remoto retornou um erro: (404) Não Localizado.
(04/11/2014 08:18) [EXCEPTION]:    em System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: Não é possível acessar um objeto descartado.
Nome do objeto: 'System.Net.Sockets.NetworkStream'.
(04/11/2014 08:19) [EXCEPTION]:    em System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: Não é possível acessar um objeto descartado.
Nome do objeto: 'SslStream'.
(04/11/2014 08:19) [EXCEPTION]:    em System.Net.Security.SslState.CheckThrow(Boolean authSucessCheck)
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:19) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:19) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:19) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:19) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: Endereço IP inválido foi especificado.
(04/11/2014 08:19) [EXCEPTION]:    em System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(04/11/2014 08:19) [LOG]: Connected and logged in astamiresantiago
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:19) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:19) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:19) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:19) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:19) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:19) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:19) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: Valor era muito grande ou muito pequeno para Int32.
(04/11/2014 08:19) [EXCEPTION]:    em System.Convert.ToInt32(Double value)
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: O servidor remoto retornou um erro: (404) Não Localizado.
(04/11/2014 08:19) [EXCEPTION]:    em System.Net.HttpWebRequest.GetResponse()
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: O servidor remoto retornou um erro: (404) Não Localizado.
(04/11/2014 08:19) [EXCEPTION]:    em System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: Endereço IP inválido foi especificado.
(04/11/2014 08:19) [EXCEPTION]:    em System.Net.IPAddress.InternalParse(String ipString, Boolean tryParse)
(04/11/2014 08:19) [LOG]: Connected and logged in asathuslol
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: Endereço IP inválido foi especificado.
Não Localizado.
(04/11/2014 08:19) [EXCEPTION]:    em System.Net.HttpWebRequest.GetResponse()
 ipString, Boolean tryParse)
(04/11/2014 08:19) [LOG]: Connected and logged in asElielsontb
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: O servidor remoto retornou um erro: (404) Não Localizado.
(04/11/2014 08:19) [EXCEPTION]:    em System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: O servidor remoto retornou um erro: (404) Não Localizado.
(04/11/2014 08:19) [EXCEPTION]:    em System.Net.HttpWebRequest.GetResponse()
(04/11/2014 08:19) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:19) [EXCEPTION]: O servidor remoto retornou um erro: (404) Não Localizado.
(04/11/2014 08:19) [EXCEPTION]:    em System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
(04/11/2014 08:21) [LOG]: Preforming LCDSHeartBeat
(04/11/2014 08:21) [LOG]: Preforming LCDSHeartBeat
(04/11/2014 08:21) [LOG]: Preforming LCDSHeartBeat
(04/11/2014 08:21) [LOG]: Preforming LCDSHeartBeat
(04/11/2014 08:21) [LOG]: Preforming LCDSHeartBeat
(04/11/2014 08:21) [LOG]: Preforming LCDSHeartBeat
(04/11/2014 08:22) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:22) [EXCEPTION]: Não é possível converter um objeto do tipo 'PVPNetConnect.TypedObject' no tipo 'System.Object[]'.
(04/11/2014 08:22) [EXCEPTION]:    em PVPNetConnect.TypedObject.GetArray(String key) na c:\Users\Betty\Desktop\Coding\LegendaryClient\PVPNetConnect\TypedObject.cs:linha 84
(04/11/2014 08:22) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:22) [EXCEPTION]: A chave fornecida não estava presente no dicionário.
(04/11/2014 08:22) [EXCEPTION]:    em System.Collections.Generic.Dictionary`2.get_Item(TKey key)
(04/11/2014 08:22) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:22) [EXCEPTION]: A chave fornecida não estava presente no dicionário.
(04/11/2014 08:22) [EXCEPTION]:    em System.Collections.Generic.Dictionary`2.get_Item(TKey key)
(04/11/2014 08:22) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:22) [EXCEPTION]: Referência de objeto não definida para uma instância de um objeto.
(04/11/2014 08:22) [EXCEPTION]:    em jabber.connection.XmppStream.Write(XmlElement elem)
(04/11/2014 08:22) [EXCEPTION]: A first chance exception was thrown
(04/11/2014 08:22) [EXCEPTION]: Referência de objeto não definida para uma instância de um objeto.
(04/11/2014 08:22) [EXCEPTION]:    em jabber.connection.XmppStream.Write(XmlElement elem)
   em jabber.connection.StreamComponent.Write(XmlElement elem)
   em jabber.connection.Room.set_Nickname(String value)
   em LegendaryClient.Windows.TeamQueuePage.<LoadStats>d__0.MoveNext() na c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\TeamQueuePage.xaml.cs:linha 105
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
(04/11/2014 08:22) [UNHANDLEDEXCEPTION]: An unhandled exception was thrown
(04/11/2014 08:22) [UNHANDLEDEXCEPTION]: Referência de objeto não definida para uma instância de um objeto.
(04/11/2014 08:22) [UNHANDLEDEXCEPTION]:    em jabber.connection.XmppStream.Write(XmlElement elem)
   em jabber.connection.StreamComponent.Write(XmlElement elem)
   em jabber.connection.Room.set_Nickname(String value)
   em LegendaryClient.Windows.TeamQueuePage.<LoadStats>d__0.MoveNext() na c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\Windows\TeamQueuePage.xaml.cs:linha 105
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__0(Object state)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   em System.Windows.Threading.DispatcherOperation.InvokeImpl()
   em System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Windows.Threading.DispatcherOperation.Invoke()
   em System.Windows.Threading.Dispatcher.ProcessQueue()
   em System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   em MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   em MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   em System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   em MS.Internal.Threading.ExceptionFilterHelper.TryCatchWhen(Object source, Delegate method, Object args, Int32 numArgs, Delegate catchHandler)
   em System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   em MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   em MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   em System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   em System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   em System.Windows.Threading.Dispatcher.Run()
   em System.Windows.Application.RunDispatcher(Object ignore)
   em System.Windows.Application.RunInternal(Window window)
   em System.Windows.Application.Run(Window window)
   em LegendaryClient.App.Main() na c:\Users\Betty\Desktop\Coding\LegendaryClient\LegendaryClient\obj\Release\App.g.cs:linha 0

**Comment by nairaner** [comment]
Its caused by relogging, for now restart client if want to change account
