### ISSUE TITLE
friends list ...

### ISSUE THREAD

**Issue by lessn** [eddy5641/LegendaryClient#99]
Is not appearing any friend on your friends list ...

**Comment by nairaner** [comment]
which region are you on?

**Comment by lessn** [comment]
Brasil server

**Comment by Dispersia** [comment]
Since I don't have a Brasil account, I don't like asking for peoples accounts but would I be able to test on yours / have you register me one(add that account as a friend as well on your league client while you're at it)? I can't get to the page to allow me to register to find out what's going on.

**Comment by lessn** [comment]
I ran as administrator and ran the friend list ... yet much of the client is working perfectly ... thanks.
